# Machine Learning non surpervisé - modèle NN : Song to Song

# **Import de librairies**

In [1]:
# =============================================================================
# BLOC D'IMPORTATIONS POUR PROJET DATA ANALYSIS - VERSION OPTIMISÉE
# =============================================================================
# Ce bloc constitue la base technique d'un environnement Data Science complet
# Organisation selon PEP-8 : imports standards, puis tiers, puis locaux
# Suppression des doublons et optimisation des commentaires


# --- IMPORTS BIBLIOTHÈQUE STANDARD PYTHON ---
# Regroupement de tous les modules de la bibliothèque standard selon PEP-8

import os  # Interface système d'exploitation (environ, getcwd, system)
import sys  # Accès aux variables de l'interpréteur Python (path, argv, exit)
import time  # Gestion temporelle (sleep, time, perf_counter pour benchmarking)
import warnings  # Système de contrôle des avertissements Python
import platform  # Informations environnement (system, machine, python_version)
import subprocess  # Exécution sécurisée de commandes système
import itertools  # Fonctions d'itération avancées (product, combinations, chain)
import pickle  # Sérialisation/désérialisation d'objets Python

# Import spécifique de datetime pour manipulation dates/heures
from datetime import datetime  # Classe datetime(year, month, day, hour, minute, second)
from pathlib import Path  # Gestion moderne des chemins de fichiers (cross-platform)
from tqdm import tqdm  # Barres de progression intelligentes avec ETA et vitesse


# --- IMPORTS BIBLIOTHÈQUES TIERCES ---
# Regroupement des packages externes selon leur domaine d'application

# MANIPULATION ET ANALYSE DE DONNÉES
import pandas as pd  # Framework analyse données tabulaires (DataFrame, Series)
import numpy as np  # Calcul numérique vectorisé (ndarray, fonctions mathématiques)

# VISUALISATION GRAPHIQUE
import matplotlib.pyplot as plt  # Moteur graphique de base (plot, show, figure)
import seaborn as sns  # Visualisations statistiques modernes sur matplotlib

# COMMUNICATION RÉSEAU
import requests  # Client HTTP élégant (get, post, put, delete avec sessions)


# --- CONFIGURATION ENVIRONNEMENT ---
# Configuration immédiate des warnings après tous les imports

# Suppression de tous les avertissements pour clarté d'affichage
# ATTENTION: peut masquer des problèmes importants, utiliser avec discernement
# Alternative: warnings.filterwarnings('ignore', category=SpecificWarning)
warnings.filterwarnings('ignore')


# =============================================================================
# RÉSUMÉ DES OPTIMISATIONS APPLIQUÉES :
#
# 1. SUPPRESSION DES DOUBLONS :
#    - os, time, warnings, platform, datetime : dédoublonnés
#    - Conservation d'une seule déclaration par import
#
# 2. RÉORGANISATION PEP-8 :
#    - Imports standard library en premier
#    - Imports tierces en second
#    - Regroupement thématique maintenu
#
# 3. OPTIMISATION COMMENTAIRES :
#    - Suppression des redondances
#    - Conservation des informations techniques essentielles
#    - Format uniforme et concis
#
# 4. MAINTIEN FONCTIONNALITÉS :
#    - Tous les modules nécessaires conservés
#    - Aliases conventionnels respectés (pd, np, plt, sns)
#    - Configuration warnings préservée
# =============================================================================

# **Chargement du dataset**

In [2]:
# =============================================================================
# SOLUTION 4 : Avec gestion des erreurs (PLUS ROBUSTE)
# =============================================================================

def charger_dataset_spotify():
    """
    Charge le dataset Spotify en testant plusieurs emplacements possibles.
    
    Returns:
        pd.DataFrame: DataFrame contenant les données Spotify
    
    Raises:
        FileNotFoundError: Si aucun fichier n'est trouvé dans les emplacements testés
    """
    
    # Liste des chemins possibles à tester
    # Path.cwd() retourne le répertoire de travail actuel (où se trouve le script)
    # Path.home() retourne le répertoire utilisateur (/Users/username sur tous les systèmes)
    # L'opérateur "/" avec pathlib fonctionne sur tous les systèmes d'exploitation
    chemins_possibles = [
        # Chemin relatif depuis le script Python courant
        Path.cwd() / "Datasets" / "df_concat_tagged.csv",
        
        # Chemin depuis le répertoire parent du script
        # .parent remonte d'un niveau dans l'arborescence
        Path.cwd().parent / "Datasets" / "df_concat_tagged.csv",
        
        # Chemin absolu depuis le répertoire utilisateur (Mac)
        Path.home() / "Documents" / "Cours" / "Wild_Code_School" / "Semaine_8_Visualisation_interactive_et_Pandas_approfondi" / "Projet_2" / "Projet_2_local" / "Datasets" / "df_concat_tagged.csv",
        
        # Chemin absolu alternatif pour différentes configurations
        Path.home() / "Documents" / "Cours" / "Wild_Code_School" / "Semaine_8_Visualisation_interactive_&_Pandas_approfondi" / "Projet_2" / "Projet_2_local" / "Datasets" / "df_concat_tagged.csv",
    ]
    
    # Parcours séquentiel des chemins jusqu'à trouver le fichier
    for chemin in chemins_possibles:
        # Path.exists() retourne True si le fichier existe, False sinon
        if chemin.exists():
            try:
                # pd.read_csv() charge le fichier CSV en DataFrame pandas
                # Paramètre chemin : Path object ou string du fichier à charger
                df = pd.read_csv(chemin)
                
                # Affichage du succès avec le chemin utilisé
                print(f"✅ Dataset chargé avec succès depuis : {chemin}")
                
                # Retour du DataFrame chargé
                return df
                
            except Exception as e:
                # Capture de toute exception lors de la lecture du fichier
                # (erreurs de format, permissions, corruption, etc.)
                print(f"❌ Erreur lors du chargement de {chemin}: {e}")
                
                # continue passe à l'itération suivante de la boucle
                continue
    
    # Si aucun fichier n'a été trouvé dans tous les chemins testés
    # raise lève une exception personnalisée
    raise FileNotFoundError("❌ Aucun dataset Spotify trouvé dans les emplacements testés")


# =============================================================================
# UTILISATION DE LA FONCTION
# =============================================================================

# try/except pour gérer l'exception potentielle de la fonction
try:
    # Appel de la fonction qui retourne le DataFrame chargé
    df = charger_dataset_spotify()
    
    # Vérification optionnelle : affichage des informations du DataFrame
    print(f"📊 Dataset chargé : {df.shape[0]} lignes, {df.shape[1]} colonnes")
    
except FileNotFoundError as e:
    # Gestion spécifique de l'erreur de fichier non trouvé
    print(e)
    
    # Arrêt du programme ou définition d'un DataFrame vide selon vos besoins
    df = None

except Exception as e:
    # Gestion de toute autre exception non prévue
    print(f"❌ Erreur inattendue : {e}")
    df = None

✅ Dataset chargé avec succès depuis : c:\Users\beber\Documents\Cours\Wild_Code_School\Semaine_8_Visualisation_interactive_&_Pandas_approfondi\Projet_2\Projet_2_local\Datasets\df_concat_tagged.csv
📊 Dataset chargé : 5403 lignes, 18 colonnes

# Machine Learning

## Import des bibliothèques de ML

In [3]:
# Importation de la fonction train_test_split du module sklearn.model_selection
# train_test_split permet de diviser un jeu de données en deux sous-ensembles : un pour l'entraînement et un pour le test.
from sklearn.model_selection import train_test_split

# Importation de la classe LabelEncoder du module sklearn.preprocessing
# LabelEncoder convertit des variables catégorielles (ex : 'chat', 'chien') en entiers (ex : 0, 1).
from sklearn.preprocessing import LabelEncoder

# Importation de la classe KNeighborsClassifier du module sklearn.neighbors
# KNeighborsClassifier est un algorithme de classification supervisé basé sur la proximité des K plus proches voisins.
from sklearn.neighbors import KNeighborsClassifier

# Importation de la classe NearestNeighbors du module sklearn.neighbors
# NearestNeighbors permet de rechercher les voisins les plus proches dans un contexte non supervisé (pas de variable cible).
from sklearn.neighbors import NearestNeighbors

# Importation des classes KMeans et DBSCAN du module sklearn.cluster
# KMeans : algorithme de clustering partitionnant les données en K groupes selon la distance aux centres.
# DBSCAN : algorithme de clustering basé sur la densité, détecte des groupes denses et les points aberrants.
from sklearn.cluster import KMeans, DBSCAN

# Importation de fonctions de scoring pour évaluer la qualité des clusters
# silhouette_score : mesure la cohésion et la séparation des clusters (proche de 1 = bons clusters)
# davies_bouldin_score : mesure la compacité et la séparation (plus faible = meilleur)
# calinski_harabasz_score : rapport entre la dispersion inter- et intra-cluster (plus élevé = meilleur)
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

# Importation de la classe PCA du module sklearn.decomposition
# PCA (Analyse en Composantes Principales) réduit la dimensionnalité des données tout en conservant la variance principale.
from sklearn.decomposition import PCA

# Importation de différents scalers pour la normalisation des données
# StandardScaler : standardise les features (moyenne=0, écart-type=1)
# MinMaxScaler : met à l'échelle les features entre 0 et 1
# RobustScaler : réduit l'influence des valeurs aberrantes en utilisant la médiane et l'IQR
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# Importation de la classe Pipeline du module sklearn.pipeline
# Pipeline permet de chaîner plusieurs étapes (prétraitement, modélisation) dans un seul objet pour simplifier le workflow.
from sklearn.pipeline import Pipeline

# Features : "valence, energy, danceability, acousticness, tempo, loudness, instrumentalness"

In [4]:
X_class = df.loc[:, ['valence', 'energy', 'danceability', 'acousticness', 'tempo', 'loudness', 'instrumentalness']]


# Affiche un titre pour indiquer le début de la section de classification avec NN
print("\n--- Classification (NN pour prédire 'genre') ---")


# Utiliser un ensemble cohérent de features pour trouver des voisins similaires
# Prenons les mêmes features que pour la classification (X_class)
# On crée un nouveau scaler et on l'entraîne sur l'ensemble de X_class
# Standardiser toutes ces features
scaler_nn = StandardScaler()
X_nn_scaled = scaler_nn.fit_transform(X_class) # Standardiser X_class



k = 5 # Nombre de voisins à trouver (y compris le point lui-même si k>0 et qu'il est dans les données)
# metric='euclidean' est la distance standard (ligne droite entre les points)
# algorithm='auto' choisit le meilleur algorithme en fonction des données
nn_model = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
# .fit() indexe les données X_nn_scaled
nn_model.fit(X_nn_scaled) # Entraîner sur les données standardisées X_class


# Diviser les données (X_class et y_class)

# stratify=y_class est crucial ici pour gérer le déséquilibre potentiel des classes
X_train_c, X_test_c = train_test_split(X_class, test_size=0.2, random_state=42)

# Sélectionner les 3 premiers points de X_test_c (qui sont non standardisés)
sample_points_original = X_test_c[:3]

# Trouver les voisins pour quelques points de l'ensemble de test (X_test_c)
# Standardiser ces points d'abord avec le scaler_knn
X_test_c_scaled_knn = scaler_nn.transform(X_test_c) # Utiliser transform

# Sélectionner les 3 premiers points de X_test_c (qui sont non standardisés)
sample_points_scaled = X_test_c_scaled_knn[:3]
# .kneighbors() prend les points standardisés et retourne distances et indices
distances, indices = nn_model.kneighbors(sample_points_scaled)


print(f"\nRecherche des {k} plus proches voisins pour 3 morceaux (basé sur les features standardisées de X_class):")
for i in range(len(sample_points_scaled)):
    # Récupérer l'index original du point exemple dans le DataFrame df
    original_index = sample_points_original.index[i]
    print(f"\n--- Voisinage pour Morceaux Exemple {i+1} (Index original: {original_index}) ---")
    print(f" valence réelle: {df.loc[original_index, 'valence']:.2f}, energy réelle: {df.loc[original_index, 'energy']:.2f}, danceability réelle: {df.loc[original_index, 'danceability']:.2f}, tempo réelle: {df.loc[original_index, 'tempo']:.2f}, loudness réelle: {df.loc[original_index, 'loudness']:.2f}, instrumentalness réelle: {df.loc[original_index, 'instrumentalness']:.2f}  ")

    # Les 'indices' renvoyés par kneighbors sont les positions (0, 1, 2...) dans X_knn_scaled
    print(f"  Indices des voisins dans X_nn_scaled: {indices[i]}")
    # Les distances correspondantes
    print(f"  Distances euclidiennes aux voisins: {distances[i]}")

    # Pour afficher les informations des voisins, il faut retrouver leurs index originaux dans df.
    # Comme X_nn_scaled a été créé à partir de X_class dans le même ordre, on peut utiliser
    # les indices[i] pour sélectionner les lignes correspondantes dans X_class, puis récupérer leurs index originaux.
    neighbor_original_indices = X_class.iloc[indices[i]].index
    print(f"  Index originaux des voisins dans le DataFrame: {list(neighbor_original_indices)}")

    # Afficher quelques caractéristiques clés des voisins trouvés à partir du df original
    print("  Infos sur les voisins trouvés (depuis df original):")
    # Sélectionner les lignes des voisins dans df et quelques colonnes pertinentes
    neighbor_info = df.loc[neighbor_original_indices][['valence', 'energy', 'danceability', 'acousticness', 'tempo', 'loudness', 'instrumentalness']]
    print(neighbor_info)



# Fonction pour trouver les k voisins d'un morceaux par ID (avec signatures de type)

def find_neighbors_by_id(
    track_id: int,                      # L'index du morceaux cible dans le DataFrame original
    k: int,                            # Le nombre de voisins à rechercher
    nn_model: NearestNeighbors,        # Le modèle NearestNeighbors entraîné
    scaler: StandardScaler,            # Le scaler (StandardScaler) entraîné sur les features utilisées par nn_model
    features_df: pd.DataFrame,         # Le DataFrame contenant SEULEMENT les features utilisées pour entraîner nn_model (ex: X_class)
    original_df: pd.DataFrame          # Le DataFrame original complet pour afficher toutes les informations
) -> None:                             # La fonction ne retourne rien, elle affiche les résultats

    if track_id not in features_df.index:
        print(f"Erreur: L'ID de morceaux {track_id} n'existe pas dans les données utilisées.")
        return 

    # Récupérer les features du morceaux cible
    track_features = features_df.loc[[track_id]] # Garder le format DataFrame

    # Standardiser les features du morceaux cible avec le même scaler
    track_features_scaled = scaler.transform(track_features)

    # Trouver les k voisins (incluant potentiellement lui-même en premier)
    distances, indices = nn_model.kneighbors(track_features_scaled, n_neighbors=k)

    # Récupérer les index originaux des voisins trouvés
    neighbor_indices_in_features_df = indices[0] # indices est [[idx1, idx2,...]]

    # S'assurer que les indices sont valides pour .iloc
    valid_indices = [idx for idx in neighbor_indices_in_features_df if idx < len(features_df)]
    if len(valid_indices) < len(neighbor_indices_in_features_df):
        print("Avertissement: Certains indices de voisins étaient hors limites.")

    if not valid_indices:
        print("Aucun voisin valide trouvé.")
        return

    # Récupérer les index originaux des voisins trouvés dans le DataFrame original
    neighbor_original_indices = features_df.iloc[valid_indices].index

    print(f"\n--- Plus proches voisins pour le morceaux avec ID {track_id} ---")
    print("Morceaux Cible:")

    # Utiliser .loc pour être sûr avec l'index original
    print(original_df.loc[[track_id]])

    print(f"\n{len(neighbor_original_indices)} plus proches voisins trouvés (basé sur les features de X_class standardisées):")

    # Utiliser .loc avec la liste des index originaux des voisins
    neighbor_info = original_df.loc[neighbor_original_indices]
    print(neighbor_info)
    print("\nDistances euclidiennes correspondantes:")

    # Afficher seulement les distances pour les voisins valides trouvés
    print(distances[0][:len(valid_indices)])



# Choisir un ID de morceaux valide (par exemple, le premier index de l'ensemble de test X_test_c)

if not X_test_c.empty:
    example_id_to_find = X_test_c.index[0]
    num_neighbors_to_find = 6 # Chercher 5 voisins + lui-même (le plus proche voisin est souvent le point lui-même avec une distance de 0)

    # Appeler la fonction avec les objets nécessaires
    find_neighbors_by_id(
        track_id=example_id_to_find,
        k=num_neighbors_to_find,
        nn_model=nn_model,         # Le modèle NearestNeighbors entraîné
        scaler=scaler_nn,   # Le scaler entraîné sur tout X_class
        features_df=X_class,       # Le DataFrame des features utilisé pour entraîner nn_model
        original_df=df             # Le DataFrame original complet
    )
else:
    print("\nL'ensemble de test X_test_c est vide, impossible de choisir un example_id pour la fonction find_neighbors_by_id.")

# Tester avec un autre ID manuellement si vous le souhaitez
# find_neighbors_by_id(track_id=5018, k=5, nn_model=nn_model, scaler=scaler_nn_unsup, features_df=X_class, original_df=df)

--- Classification (NN pour prédire 'genre') ---

Recherche des 5 plus proches voisins pour 3 morceaux (basé sur les features standardisées de X_class):

--- Voisinage pour Morceaux Exemple 1 (Index original: 5018) ---
 valence réelle: 0.40, energy réelle: 0.50, danceability réelle: 0.59, tempo réelle: 144.97, loudness réelle: -10.76, instrumentalness réelle: 0.78
  Indices des voisins dans X_nn_scaled: [5018  460  715  486  895]
  Distances euclidiennes aux voisins: [0.         1.53559961 1.61584786 1.70150047 1.83938587]
  Index originaux des voisins dans le DataFrame: [5018, 460, 715, 486, 895]
  Infos sur les voisins trouvés (depuis df original):
      valence  energy  danceability  acousticness    tempo  loudness  \
5018   0.4010   0.497         0.587         0.723  144.972   -10.757
460    0.3500   0.480         0.543         0.433  159.969   -14.551
715    0.0763   0.468         0.499         0.795  141.463    -9.995
486    0.3970   0.462         0.423         0.442  160.578   -14.304
895    0.1280   0.408         0.457         0.803  117.052   -11.474

      instrumentalness
5018             0.782
460              0.886
715              0.880
486              0.705
895              0.884

--- Voisinage pour Morceaux Exemple 2 (Index original: 4913) ---
 valence réelle: 0.14, energy réelle: 0.49, danceability réelle: 0.86, tempo réelle: 77.46, loudness réelle: -8.51, instrumentalness réelle: 0.00
  Indices des voisins dans X_nn_scaled: [4913 2522 1242 4022 1964]
  Distances euclidiennes aux voisins: [0.         0.         0.51242599 0.51242599 0.56695317]
  Index originaux des voisins dans le DataFrame: [4913, 2522, 1242, 4022, 1964]
  Infos sur les voisins trouvés (depuis df original):
      valence  energy  danceability  acousticness   tempo  loudness  \
4913   0.1370   0.494         0.859      0.043000  77.456    -8.505
2522   0.1370   0.494         0.859      0.043000  77.456    -8.505
1242   0.1830   0.550         0.810      0.011400  76.503    -7.460
4022   0.1830   0.550         0.810      0.011400  76.503    -7.460
1964   0.0703   0.410         0.879      0.000897  80.011    -9.233

      instrumentalness
4913          0.000000
2522          0.000000
1242          0.000006
4022          0.000006
1964          0.000021

--- Voisinage pour Morceaux Exemple 3 (Index original: 1807) ---
 valence réelle: 0.18, energy réelle: 0.64, danceability réelle: 0.83, tempo réelle: 145.00, loudness réelle: -4.29, instrumentalness réelle: 0.00
  Indices des voisins dans X_nn_scaled: [1807 3098 3032 2266 3316]
  Distances euclidiennes aux voisins: [0.         0.1126054  0.17155621 0.35341695 0.43793633]
  Index originaux des voisins dans le DataFrame: [1807, 3098, 3032, 2266, 3316]
  Infos sur les voisins trouvés (depuis df original):
      valence  energy  danceability  acousticness    tempo  loudness  \
1807    0.181   0.642         0.827      0.009050  145.004    -4.290
3098    0.179   0.650         0.811      0.001250  146.028    -4.410
3032    0.184   0.661         0.847      0.000807  143.979    -4.614
2266    0.211   0.703         0.836      0.031000  144.959    -4.731
3316    0.177   0.646         0.778      0.091200  140.040    -4.657

      instrumentalness
1807          0.000002
3098          0.000000
3032          0.001260
2266          0.000000
3316          0.000000

--- Plus proches voisins pour le morceaux avec ID 5018 ---
Morceaux Cible:
       artist_name         track_name                track_id  popularity  \
5018  radical face  welcome home, son  6HTVZeVQ9J6Uiq6tHESxU9          68

      acousticness  danceability  duration_ms  energy  instrumentalness  \
5018         0.723         0.587       287634   0.497             0.782

      liveness  loudness  speechiness    tempo time_signature  valence genre  \
5018     0.142   -10.757       0.0307  144.972              3    0.401   pop

     tags_humeur tags_activité
5018  #energique  #dance/#fête

6 plus proches voisins trouvés (basé sur les features de X_class standardisées):
         artist_name             track_name                track_id  \
5018    radical face      welcome home, son  6HTVZeVQ9J6Uiq6tHESxU9
460        Daft Punk              Disc Wars  6sa8y1XKi2ljJd0z6sUEz3
715   blonde redhead   for the damaged coda  7jA5OcunWRSYXq98puhAX8
486        Daft Punk          Encom Part II  7Ki3gVxLvvoEX6KFJaL11x
895        novo amor                 anchor  7qH9Z4dJEN0l9bidizW7fq
4612     mac demarco  chamber of reflection  1MJ5f5EYBC92ADD6xcz7nb

      popularity  acousticness  danceability  duration_ms  energy  \
5018          68         0.723         0.587       287634   0.497
460           44         0.433         0.543       251440   0.480
715           65         0.795         0.499       157000   0.468
486           22         0.442         0.423       137667   0.462
895           68         0.803         0.457       257533   0.408
4612          71         0.263         0.537       231724   0.558

      instrumentalness  liveness  loudness  speechiness    tempo  \
5018             0.782    0.1420   -10.757       0.0307  144.972
460              0.886    0.1170   -14.551       0.0304  159.969
715              0.880    0.0899    -9.995       0.0396  141.463
486              0.705    0.1070   -14.304       0.0364  160.578
895              0.884    0.1260   -11.474       0.0307  117.052
4612             0.910    0.1020    -8.678       0.0929  131.037

     time_signature  valence              genre tags_humeur   tags_activité
5018              3   0.4010                pop  #energique    #dance/#fête
460             4/4   0.3500  variété française  #energique    #dance/#fête
715               4   0.0763         jazz/blues     #triste  #sport/#cardio
486             4/4   0.3970  variété française  #energique  #sport/#cardio
895               4   0.1280         jazz/blues     #triste  #sport/#cardio
4612              4   0.5050                pop  #energique    #dance/#fête

Distances euclidiennes correspondantes:
[0.         1.53559961 1.61584786 1.70150047 1.83938587 1.92125037]

# Tests différentes configurations

## Tests NN + K-means et DBSCAN (différentes configuration), sans génération pdf

### Version 1

In [5]:
# CHARGEMENT AUTOMATIQUE DES DONNÉES SELON LE SYSTÈME D'EXPLOITATION
def charger_donnees():
    """
    Charge les données Spotify depuis le fichier CSV approprié selon l'OS
    
    Retourne:
    DataFrame : Données Spotify chargées
    """
    # Détection du système d'exploitation
    system = platform.system()
    
    # Définition des chemins selon l'OS
    if system == "Windows":
        # Chemin pour Windows
        chemin_fichier = r"C:\Users\beber\Documents\Cours\Wild_Code_School\Semaine_8_Visualisation_interactive_&_Pandas_approfondi\Projet_2\Projet_2_local\Datasets\df_concat_tagged.csv"
    else:
        # Chemin pour Mac/Linux
        chemin_fichier = "/Users/bertranddevulder/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_et_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/df_concat_tagged.csv"
    
    try:
        # Tentative de chargement avec le chemin automatique
        df_spotify = pd.read_csv(chemin_fichier)
        print(f"Données chargées avec succès depuis: {chemin_fichier}")
        print(f"Forme du DataFrame: {df_spotify.shape}")
        return df_spotify
    except FileNotFoundError:
        # Si le fichier n'est pas trouvé, essayer des chemins alternatifs
        chemins_alternatifs = [
            "/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/df_concat_tagged.csv",
            "./Datasets/df_concat_tagged.csv",
            "./df_concat_tagged.csv",
            "df_concat_tagged.csv"
        ]
        
        for chemin in chemins_alternatifs:
            try:
                df_spotify = pd.read_csv(chemin)
                print(f"Données chargées avec succès depuis: {chemin}")
                print(f"Forme du DataFrame: {df_spotify.shape}")
                return df_spotify
            except FileNotFoundError:
                continue
        
        # Si aucun chemin ne fonctionne, lever une erreur
        raise FileNotFoundError("Impossible de trouver le fichier df_concat_tagged.csv. Vérifiez le chemin.")

def test_clustering_configurations(df_spotify):
    """
    Fonction principale pour tester toutes les configurations de clustering
    
    Arguments:
    df_spotify : DataFrame contenant les données Spotify avec les features audio
    
    Retourne:
    dict : Dictionnaire contenant tous les résultats des tests
    """
    
    # Affichage des informations sur le DataFrame
    print(f"Colonnes disponibles: {list(df_spotify.columns)}")
    print(f"Nombre de lignes: {len(df_spotify)}")
    
    # Définition des différents cas de features à tester
    # Cas 1 : 7 features complètes incluant instrumentalness
    features_cas1 = ['valence', 'energy', 'danceability', 'acousticness', 
                     'tempo', 'loudness', 'instrumentalness']
    # Cas 2 : 6 features sans instrumentalness  
    features_cas2 = ['valence', 'energy', 'danceability', 'acousticness', 
                     'tempo', 'loudness']
    # Cas 3 : 5 features essentielles pour l'émotion musicale
    features_cas3 = ['valence', 'energy', 'danceability', 'acousticness', 'tempo']
    
    cases_features = {
        'cas1': features_cas1,
        'cas2': features_cas2, 
        'cas3': features_cas3
    }
    
    # Vérification de la disponibilité des features dans le DataFrame
    print("\nVérification des features disponibles:")
    for cas_nom, features in cases_features.items():
        features_manquantes = [f for f in features if f not in df_spotify.columns]
        if features_manquantes:
            print(f"ATTENTION - {cas_nom}: Features manquantes: {features_manquantes}")
        else:
            print(f"OK - {cas_nom}: Toutes les features disponibles")
    
    # Paramètres à tester pour le clustering
    k_values = [2, 3, 4, 5, 7, 10, 15, 20, 25]  # Suppression de k=1 car impossible pour le clustering
    distance_metrics = ['euclidean', 'manhattan']  # Métriques de distance
    algorithms = ['auto', 'ball_tree', 'kd_tree']  # Algorithmes pour NearestNeighbors
    scalers = {
        'StandardScaler': StandardScaler(),  # Standardisation avec moyenne=0, écart-type=1
        'MinMaxScaler': MinMaxScaler(),      # Normalisation entre 0 et 1
        'RobustScaler': RobustScaler()       # Normalisation robuste aux outliers
    }
    
    # Paramètres DBSCAN - eps et min_samples sont cruciaux pour la performance
    eps_values = [0.3, 0.5, 0.7, 1.0, 1.5]  # Rayon de voisinage
    min_samples_values = [3, 5, 7, 10]       # Nombre minimum de points pour former un cluster
    
    resultats = []  # Stockage de tous les résultats
    
    print("\nDébut des tests de clustering...")
    
    # Boucle principale pour tester toutes les combinaisons
    for cas_nom, features in cases_features.items():
        print(f"\nTest du {cas_nom} avec {len(features)} features")
        
        # Vérification que toutes les features existent dans le DataFrame
        features_disponibles = [f for f in features if f in df_spotify.columns]
        if len(features_disponibles) != len(features):
            print(f"ERREUR: Certaines features manquantes pour {cas_nom}")
            continue
            
        # Extraction des données pour ce cas
        X = df_spotify[features_disponibles].copy()
        
        # Nettoyage des données - suppression des valeurs manquantes et infinies
        print(f"Données avant nettoyage: {len(X)} lignes")
        X = X.dropna()
        X = X.replace([np.inf, -np.inf], np.nan).dropna()
        print(f"Données après nettoyage: {len(X)} lignes")
        
        if len(X) < 100:  # Vérification d'un minimum de données
            print(f"ERREUR: Pas assez de données pour {cas_nom} ({len(X)} lignes)")
            continue
            
        for scaler_nom, scaler in scalers.items():
            print(f"  Test avec {scaler_nom}...")
            
            try:
                # Application du prétraitement - scaling des données
                scaler_fitted = scaler.fit(X)
                X_scaled = scaler_fitted.transform(X)
                
                # Test des modèles K-means
                for k in k_values:
                    if k > len(X):  # K ne peut pas être supérieur au nombre d'échantillons
                        continue
                        
                    try:
                        # Initialisation et entraînement du modèle K-means
                        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
                        kmeans_labels = kmeans.fit_predict(X_scaled)
                        
                        # Vérification qu'il y a effectivement k clusters différents
                        if len(np.unique(kmeans_labels)) < 2:
                            continue
                            
                        # Calcul des métriques d'évaluation
                        # Silhouette Score : mesure la cohésion intra-cluster et séparation inter-cluster
                        # Valeurs entre -1 et 1, plus c'est proche de 1, mieux c'est
                        sil_score = silhouette_score(X_scaled, kmeans_labels)
                        
                        # Davies-Bouldin Score : mesure la similarité intra-cluster vs distance inter-cluster  
                        # Plus la valeur est faible, meilleur est le clustering
                        db_score = davies_bouldin_score(X_scaled, kmeans_labels)
                        
                        # Calinski-Harabasz Score : ratio de la dispersion inter-cluster sur intra-cluster
                        # Plus la valeur est élevée, meilleur est le clustering
                        ch_score = calinski_harabasz_score(X_scaled, kmeans_labels)
                        
                        # Stockage des résultats K-means
                        resultats.append({
                            'cas': cas_nom,
                            'features_count': len(features_disponibles),
                            'scaler': scaler_nom,
                            'modele': 'KMeans',
                            'k_clusters': k,
                            'silhouette_score': sil_score,
                            'davies_bouldin_score': db_score,
                            'calinski_harabasz_score': ch_score,
                            'n_samples': len(X_scaled),
                            'features_list': ', '.join(features_disponibles)
                        })
                        
                    except Exception as e:
                        print(f"    Erreur K-means k={k}: {str(e)}")
                        continue
                
                # Test des modèles DBSCAN
                for eps in eps_values:
                    for min_samples in min_samples_values:
                        try:
                            # Initialisation et entraînement du modèle DBSCAN
                            # DBSCAN identifie les clusters de densité variable et détecte le bruit
                            dbscan = DBSCAN(eps=eps, min_samples=min_samples)
                            dbscan_labels = dbscan.fit_predict(X_scaled)
                            
                            # Vérification qu'il y a des clusters (pas que du bruit)
                            n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
                            if n_clusters < 2:
                                continue
                                
                            # Exclusion du bruit (label -1) pour le calcul des métriques
                            mask = dbscan_labels != -1
                            if np.sum(mask) < 10:  # Au moins 10 points non-bruit
                                continue
                                
                            X_no_noise = X_scaled[mask]
                            labels_no_noise = dbscan_labels[mask]
                            
                            # Calcul des métriques d'évaluation
                            sil_score = silhouette_score(X_no_noise, labels_no_noise)
                            db_score = davies_bouldin_score(X_no_noise, labels_no_noise)
                            ch_score = calinski_harabasz_score(X_no_noise, labels_no_noise)
                            
                            # Stockage des résultats DBSCAN
                            resultats.append({
                                'cas': cas_nom,
                                'features_count': len(features_disponibles),
                                'scaler': scaler_nom,
                                'modele': 'DBSCAN',
                                'eps': eps,
                                'min_samples': min_samples,
                                'n_clusters': n_clusters,
                                'noise_points': np.sum(dbscan_labels == -1),
                                'silhouette_score': sil_score,
                                'davies_bouldin_score': db_score,
                                'calinski_harabasz_score': ch_score,
                                'n_samples': len(X_scaled),
                                'features_list': ', '.join(features_disponibles)
                            })
                            
                        except Exception as e:
                            print(f"    Erreur DBSCAN eps={eps}, min_samples={min_samples}: {str(e)}")
                            continue
                            
            except Exception as e:
                print(f"  Erreur preprocessing {scaler_nom}: {str(e)}")
                continue
    
    print(f"\nTests terminés. Nombre total de configurations testées: {len(resultats)}")
    return resultats

def analyser_resultats(resultats):
    """
    Analyse des résultats et génération des Top 5
    
    Arguments:
    resultats : Liste des dictionnaires contenant tous les résultats
    
    Retourne:
    dict : Analyses et Top 5 organisés
    """
    
    if not resultats:
        print("Aucun résultat à analyser")
        return {}
    
    df_resultats = pd.DataFrame(resultats)
    
    # Séparation des résultats par modèle
    kmeans_results = df_resultats[df_resultats['modele'] == 'KMeans'].copy()
    dbscan_results = df_resultats[df_resultats['modele'] == 'DBSCAN'].copy()
    
    analyses = {}
    
    # TOP 5 K-MEANS
    print("\n" + "="*80)
    print("TOP 5 MEILLEURS RÉSULTATS K-MEANS")
    print("="*80)
    
    if not kmeans_results.empty:
        # Tri par silhouette_score décroissant (meilleur = plus élevé)
        top5_kmeans_sil = kmeans_results.nlargest(5, 'silhouette_score')
        print("\nTOP 5 - Silhouette Score (meilleur = plus élevé):")
        for idx, (i, row) in enumerate(top5_kmeans_sil.iterrows(), 1):
            print(f"{idx}. Score: {row['silhouette_score']:.4f} | "
                  f"Cas: {row['cas']} | Scaler: {row['scaler']} | "
                  f"K-clusters: {row['k_clusters']} | Samples: {row['n_samples']}")
        
        # Tri par davies_bouldin_score croissant (meilleur = plus faible)
        top5_kmeans_db = kmeans_results.nsmallest(5, 'davies_bouldin_score')
        print("\nTOP 5 - Davies-Bouldin Score (meilleur = plus faible):")
        for idx, (i, row) in enumerate(top5_kmeans_db.iterrows(), 1):
            print(f"{idx}. Score: {row['davies_bouldin_score']:.4f} | "
                  f"Cas: {row['cas']} | Scaler: {row['scaler']} | "
                  f"K-clusters: {row['k_clusters']} | Samples: {row['n_samples']}")
        
        # Tri par calinski_harabasz_score décroissant (meilleur = plus élevé)
        top5_kmeans_ch = kmeans_results.nlargest(5, 'calinski_harabasz_score')
        print("\nTOP 5 - Calinski-Harabasz Score (meilleur = plus élevé):")
        for idx, (i, row) in enumerate(top5_kmeans_ch.iterrows(), 1):
            print(f"{idx}. Score: {row['calinski_harabasz_score']:.4f} | "
                  f"Cas: {row['cas']} | Scaler: {row['scaler']} | "
                  f"K-clusters: {row['k_clusters']} | Samples: {row['n_samples']}")
    
    # TOP 5 DBSCAN
    print("\n" + "="*80)
    print("TOP 5 MEILLEURS RÉSULTATS DBSCAN")
    print("="*80)
    
    if not dbscan_results.empty:
        # Tri par silhouette_score décroissant
        top5_dbscan_sil = dbscan_results.nlargest(5, 'silhouette_score')
        print("\nTOP 5 - Silhouette Score (meilleur = plus élevé):")
        for idx, (i, row) in enumerate(top5_dbscan_sil.iterrows(), 1):
            print(f"{idx}. Score: {row['silhouette_score']:.4f} | "
                  f"Cas: {row['cas']} | Scaler: {row['scaler']} | "
                  f"EPS: {row['eps']} | Min-samples: {row['min_samples']} | "
                  f"Clusters: {row['n_clusters']} | Bruit: {row['noise_points']}")
        
        # Tri par davies_bouldin_score croissant
        top5_dbscan_db = dbscan_results.nsmallest(5, 'davies_bouldin_score')
        print("\nTOP 5 - Davies-Bouldin Score (meilleur = plus faible):")
        for idx, (i, row) in enumerate(top5_dbscan_db.iterrows(), 1):
            print(f"{idx}. Score: {row['davies_bouldin_score']:.4f} | "
                  f"Cas: {row['cas']} | Scaler: {row['scaler']} | "
                  f"EPS: {row['eps']} | Min-samples: {row['min_samples']} | "
                  f"Clusters: {row['n_clusters']} | Bruit: {row['noise_points']}")
        
        # Tri par calinski_harabasz_score décroissant
        top5_dbscan_ch = dbscan_results.nlargest(5, 'calinski_harabasz_score')
        print("\nTOP 5 - Calinski-Harabasz Score (meilleur = plus élevé):")
        for idx, (i, row) in enumerate(top5_dbscan_ch.iterrows(), 1):
            print(f"{idx}. Score: {row['calinski_harabasz_score']:.4f} | "
                  f"Cas: {row['cas']} | Scaler: {row['scaler']} | "
                  f"EPS: {row['eps']} | Min-samples: {row['min_samples']} | "
                  f"Clusters: {row['n_clusters']} | Bruit: {row['noise_points']}")
    
    # TOP 5 GLOBAL - Combinaison des meilleurs modèles
    print("\n" + "="*80)
    print("TOP 5 MEILLEURS MODÈLES GLOBAUX")
    print("="*80)
    
    # Normalisation des scores pour comparaison inter-modèles
    # Création d'un score composite basé sur les 3 métriques
    df_resultats_copy = df_resultats.copy()
    
    # Normalisation min-max des scores entre 0 et 1
    df_resultats_copy['sil_norm'] = (df_resultats_copy['silhouette_score'] - df_resultats_copy['silhouette_score'].min()) / (df_resultats_copy['silhouette_score'].max() - df_resultats_copy['silhouette_score'].min())
    df_resultats_copy['db_norm'] = 1 - ((df_resultats_copy['davies_bouldin_score'] - df_resultats_copy['davies_bouldin_score'].min()) / (df_resultats_copy['davies_bouldin_score'].max() - df_resultats_copy['davies_bouldin_score'].min()))
    df_resultats_copy['ch_norm'] = (df_resultats_copy['calinski_harabasz_score'] - df_resultats_copy['calinski_harabasz_score'].min()) / (df_resultats_copy['calinski_harabasz_score'].max() - df_resultats_copy['calinski_harabasz_score'].min())
    
    # Score composite : moyenne pondérée des 3 métriques normalisées
    df_resultats_copy['score_composite'] = (df_resultats_copy['sil_norm'] * 0.4 + 
                                           df_resultats_copy['db_norm'] * 0.3 + 
                                           df_resultats_copy['ch_norm'] * 0.3)
    
    top5_global = df_resultats_copy.nlargest(5, 'score_composite')
    print("\nTOP 5 - Score Composite (silhouette 40% + davies-bouldin 30% + calinski-harabasz 30%):")
    for idx, (i, row) in enumerate(top5_global.iterrows(), 1):
        config_details = ""
        if row['modele'] == 'KMeans':
            config_details = f"K-clusters: {row['k_clusters']}"
        else:
            config_details = f"EPS: {row['eps']} | Min-samples: {row['min_samples']} | Clusters: {row['n_clusters']}"
        
        print(f"{idx}. Score: {row['score_composite']:.4f} | "
              f"Modèle: {row['modele']} | Cas: {row['cas']} | "
              f"Scaler: {row['scaler']} | {config_details}")
    
    # ANALYSE GLOBALE DES PARAMÈTRES INFLUENTS
    print("\n" + "="*80)
    print("ANALYSE GLOBALE DES PARAMÈTRES INFLUENTS")
    print("="*80)
    
    # Analyse par cas de features
    print("\nINFLUENCE DU NOMBRE DE FEATURES:")
    for cas in df_resultats['cas'].unique():
        subset = df_resultats[df_resultats['cas'] == cas]
        avg_sil = subset['silhouette_score'].mean()
        std_sil = subset['silhouette_score'].std()
        print(f"- {cas} ({subset.iloc[0]['features_count']} features): "
              f"Silhouette moyen = {avg_sil:.4f} ± {std_sil:.4f}")
    
    # Analyse par scaler
    print("\nINFLUENCE DU TYPE DE SCALING:")
    for scaler in df_resultats['scaler'].unique():
        subset = df_resultats[df_resultats['scaler'] == scaler]
        avg_sil = subset['silhouette_score'].mean()
        std_sil = subset['silhouette_score'].std()
        print(f"- {scaler}: Silhouette moyen = {avg_sil:.4f} ± {std_sil:.4f}")
    
    # Analyse par modèle
    print("\nPERFORMANCE COMPARATIVE DES MODÈLES:")
    for modele in df_resultats['modele'].unique():
        subset = df_resultats[df_resultats['modele'] == modele]
        avg_sil = subset['silhouette_score'].mean()
        avg_db = subset['davies_bouldin_score'].mean()
        avg_ch = subset['calinski_harabasz_score'].mean()
        print(f"- {modele}: Sil={avg_sil:.4f}, DB={avg_db:.4f}, CH={avg_ch:.2f}")
    
    print("\n" + "="*80)
    print("RECOMMANDATIONS POUR LE DÉPLOIEMENT")
    print("="*80)
    
    best_model = top5_global.iloc[0]
    print(f"\nMEILLEUR MODÈLE RECOMMANDÉ:")
    print(f"- Modèle: {best_model['modele']}")
    print(f"- Cas de features: {best_model['cas']}")
    print(f"- Préprocessing: {best_model['scaler']}")
    print(f"- Features utilisées: {best_model['features_list']}")
    
    if best_model['modele'] == 'KMeans':
        print(f"- Nombre de clusters: {best_model['k_clusters']}")
        print(f"\nCODE POUR LE DÉPLOIEMENT:")
        print(f"# Chargement et preprocessing")
        print(f"from sklearn.preprocessing import {best_model['scaler']}")
        print(f"from sklearn.cluster import KMeans")
        print(f"")
        print(f"# Sélection des features")
        print(f"features = {best_model['features_list'].split(', ')}")
        print(f"X = df[features]")
        print(f"")
        print(f"# Preprocessing")
        print(f"scaler = {best_model['scaler']}()")
        print(f"X_scaled = scaler.fit_transform(X)")
        print(f"")
        print(f"# Modèle")
        print(f"model = KMeans(n_clusters={best_model['k_clusters']}, random_state=42)")
        print(f"clusters = model.fit_predict(X_scaled)")
        print(f"")
        print(f"# Score de qualité attendu: {best_model['silhouette_score']:.4f}")
    else:
        print(f"- EPS: {best_model['eps']}")
        print(f"- Min samples: {best_model['min_samples']}")
        print(f"- Clusters détectés: {best_model['n_clusters']}")
        print(f"\nCODE POUR LE DÉPLOIEMENT:")
        print(f"# Chargement et preprocessing")
        print(f"from sklearn.preprocessing import {best_model['scaler']}")
        print(f"from sklearn.cluster import DBSCAN")
        print(f"")
        print(f"# Sélection des features")
        print(f"features = {best_model['features_list'].split(', ')}")
        print(f"X = df[features]")
        print(f"")
        print(f"# Preprocessing")
        print(f"scaler = {best_model['scaler']}()")
        print(f"X_scaled = scaler.fit_transform(X)")
        print(f"")
        print(f"# Modèle")
        print(f"model = DBSCAN(eps={best_model['eps']}, min_samples={best_model['min_samples']})")
        print(f"clusters = model.fit_predict(X_scaled)")
        print(f"")
        print(f"# Score de qualité attendu: {best_model['silhouette_score']:.4f}")
    
    # EXPLICATION DES MÉTRIQUES
    print("\n" + "="*80)
    print("EXPLICATION DES MÉTRIQUES D'ÉVALUATION")
    print("="*80)
    
    print("\n1. SILHOUETTE SCORE:")
    print("   - Mesure la cohésion intra-cluster vs séparation inter-cluster")
    print("   - Valeurs entre -1 et 1, optimal proche de 1")
    print("   - Indique si les points sont bien assignés à leur cluster")
    print("   - Pénalise les clusters trop proches ou mal séparés")
    
    print("\n2. DAVIES-BOULDIN SCORE:")
    print("   - Mesure la similarité moyenne entre chaque cluster et son plus similaire")
    print("   - Plus la valeur est faible, meilleur est le clustering")
    print("   - Évalue la compacité intra-cluster et la séparation inter-cluster")
    print("   - Particulièrement sensible aux clusters de formes sphériques")
    
    print("\n3. CALINSKI-HARABASZ SCORE:")
    print("   - Ratio de la variance inter-cluster sur la variance intra-cluster")
    print("   - Plus la valeur est élevée, meilleur est le clustering")
    print("   - Favorise les clusters compacts et bien séparés")
    print("   - Aussi appelé Variance Ratio Criterion")
    
    print("\n" + "="*80)
    print("CONSEILS D'UTILISATION EN PRODUCTION")
    print("="*80)
    
    print("\n1. PRÉPARATION DES DONNÉES:")
    print("   - Appliquer le même preprocessing que lors de l'entraînement")
    print("   - Vérifier la qualité des données d'entrée")
    print("   - Gérer les valeurs manquantes de manière cohérente")
    
    print("\n2. MONITORING:")
    print("   - Surveiller la distribution des clusters au fil du temps")
    print("   - Recalculer périodiquement les métriques sur de nouvelles données")
    print("   - Réentraîner le modèle si les performances se dégradent")
    
    print("\n3. INTERPRÉTATION:")
    print("   - Analyser les caractéristiques moyennes de chaque cluster")
    print("   - Créer des profils musicaux basés sur les clusters")
    print("   - Utiliser pour la recommandation ou la classification automatique")
    
    # Sauvegarde des résultats
    try:
        df_resultats.to_csv('resultats_clustering_complets.csv', index=False)
        top5_global.to_csv('top5_meilleurs_modeles.csv', index=False)
        print(f"\nRésultats sauvegardés dans:")
        print(f"- resultats_clustering_complets.csv")
        print(f"- top5_meilleurs_modeles.csv")
    except Exception as e:
        print(f"Erreur lors de la sauvegarde: {e}")
    
    return {
        'tous_resultats': df_resultats,
        'top5_global': top5_global,
        'meilleur_modele': best_model,
        'analyses': analyses
    }

# FONCTION PRINCIPALE D'EXÉCUTION
def executer_tests_complets():
    """
    Fonction principale pour exécuter tous les tests de clustering
    
    Cette fonction orchestre l'ensemble du processus de test:
    1. Charge les données depuis le fichier CSV
    2. Teste toutes les configurations possibles
    3. Analyse les résultats 
    4. Génère les recommandations
    
    Retourne:
    dict : Résultats complets de l'analyse
    """
    
    print("DÉBUT DE L'ANALYSE COMPLÈTE DES MODÈLES DE CLUSTERING")
    print("="*80)
    print(f"Système d'exploitation détecté: {platform.system()}")
    
    try:
        # Chargement des données
        df_spotify = charger_donnees()
        
        # Exécution de tous les tests
        resultats = test_clustering_configurations(df_spotify)
        
        if not resultats:
            print("ERREUR: Aucun résultat généré")
            return None
        
        print(f"\nNOMBRE TOTAL DE CONFIGURATIONS TESTÉES: {len(resultats)}")
        
        # Analyse des résultats
        analyses = analyser_resultats(resultats)
        
        print("\nANALYSE TERMINÉE AVEC SUCCÈS!")
        
        return analyses
        
    except Exception as e:
        print(f"ERREUR LORS DE L'EXÉCUTION: {e}")
        return None

# EXÉCUTION AUTOMATIQUE
if __name__ == "__main__":
    resultats_finaux = executer_tests_complets()

DÉBUT DE L'ANALYSE COMPLÈTE DES MODÈLES DE CLUSTERING
================================================================================
Système d'exploitation détecté: Windows
Données chargées avec succès depuis: C:\Users\beber\Documents\Cours\Wild_Code_School\Semaine_8_Visualisation_interactive_&_Pandas_approfondi\Projet_2\Projet_2_local\Datasets\df_concat_tagged.csv
Forme du DataFrame: (5403, 18)
Colonnes disponibles: ['artist_name', 'track_name', 'track_id', 'popularity', 'acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'time_signature', 'valence', 'genre', 'tags_humeur', 'tags_activité']
Nombre de lignes: 5403

Vérification des features disponibles:
OK - cas1: Toutes les features disponibles
OK - cas2: Toutes les features disponibles
OK - cas3: Toutes les features disponibles

Début des tests de clustering...

Test du cas1 avec 7 features
Données avant nettoyage: 5403 lignes
Données après nettoyage: 5403 lignes
  Test avec StandardScaler...

  File "c:\Users\beber\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\beber\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\beber\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\beber\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Test avec MinMaxScaler...
  Test avec RobustScaler...

Test du cas2 avec 6 features
Données avant nettoyage: 5403 lignes
Données après nettoyage: 5403 lignes
  Test avec StandardScaler...
  Test avec MinMaxScaler...
  Test avec RobustScaler...

Test du cas3 avec 5 features
Données avant nettoyage: 5403 lignes
Données après nettoyage: 5403 lignes
  Test avec StandardScaler...
  Test avec MinMaxScaler...
  Test avec RobustScaler...

Tests terminés. Nombre total de configurations testées: 166

NOMBRE TOTAL DE CONFIGURATIONS TESTÉES: 166

================================================================================
TOP 5 MEILLEURS RÉSULTATS K-MEANS
================================================================================

TOP 5 - Silhouette Score (meilleur = plus élevé):
1. Score: 0.9616 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 2.0 | Samples: 5403
2. Score: 0.9523 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 3.0 | Samples: 5403
3. Score: 0.9463 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 4.0 | Samples: 5403
4. Score: 0.9426 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 5.0 | Samples: 5403
5. Score: 0.9370 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 7.0 | Samples: 5403

TOP 5 - Davies-Bouldin Score (meilleur = plus faible):
1. Score: 0.1673 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 2.0 | Samples: 5403
2. Score: 0.3279 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 3.0 | Samples: 5403
3. Score: 0.4107 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 4.0 | Samples: 5403
4. Score: 0.4217 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 5.0 | Samples: 5403
5. Score: 0.4634 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 7.0 | Samples: 5403

TOP 5 - Calinski-Harabasz Score (meilleur = plus élevé):
1. Score: 654560.9205 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 25.0 | Samples: 5403
2. Score: 507085.6026 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 20.0 | Samples: 5403
3. Score: 378526.1889 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 15.0 | Samples: 5403
4. Score: 262708.2718 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 10.0 | Samples: 5403
5. Score: 193252.9438 | Cas: cas1 | Scaler: RobustScaler | K-clusters: 7.0 | Samples: 5403

================================================================================
TOP 5 MEILLEURS RÉSULTATS DBSCAN
================================================================================

TOP 5 - Silhouette Score (meilleur = plus élevé):
1. Score: 0.8005 | Cas: cas1 | Scaler: RobustScaler | EPS: 1.5 | Min-samples: 3.0 | Clusters: 24.0 | Bruit: 780.0
2. Score: 0.7656 | Cas: cas1 | Scaler: RobustScaler | EPS: 0.3 | Min-samples: 10.0 | Clusters: 2.0 | Bruit: 5383.0
3. Score: 0.7328 | Cas: cas1 | Scaler: RobustScaler | EPS: 1.5 | Min-samples: 7.0 | Clusters: 4.0 | Bruit: 904.0
4. Score: 0.7255 | Cas: cas3 | Scaler: StandardScaler | EPS: 0.3 | Min-samples: 7.0 | Clusters: 9.0 | Bruit: 5315.0
5. Score: 0.7196 | Cas: cas1 | Scaler: StandardScaler | EPS: 0.3 | Min-samples: 5.0 | Clusters: 9.0 | Bruit: 5354.0

TOP 5 - Davies-Bouldin Score (meilleur = plus faible):
1. Score: 0.2754 | Cas: cas2 | Scaler: RobustScaler | EPS: 1.0 | Min-samples: 7.0 | Clusters: 2.0 | Bruit: 33.0
2. Score: 0.3254 | Cas: cas1 | Scaler: RobustScaler | EPS: 0.3 | Min-samples: 10.0 | Clusters: 2.0 | Bruit: 5383.0
3. Score: 0.4015 | Cas: cas1 | Scaler: StandardScaler | EPS: 0.3 | Min-samples: 5.0 | Clusters: 9.0 | Bruit: 5354.0
4. Score: 0.4061 | Cas: cas2 | Scaler: StandardScaler | EPS: 0.3 | Min-samples: 5.0 | Clusters: 10.0 | Bruit: 5345.0
5. Score: 0.4210 | Cas: cas3 | Scaler: StandardScaler | EPS: 0.3 | Min-samples: 7.0 | Clusters: 9.0 | Bruit: 5315.0

TOP 5 - Calinski-Harabasz Score (meilleur = plus élevé):
1. Score: 3472722.3310 | Cas: cas1 | Scaler: RobustScaler | EPS: 1.5 | Min-samples: 3.0 | Clusters: 24.0 | Bruit: 780.0
2. Score: 23952.4375 | Cas: cas1 | Scaler: RobustScaler | EPS: 0.7 | Min-samples: 3.0 | Clusters: 17.0 | Bruit: 1494.0
3. Score: 13535.6602 | Cas: cas1 | Scaler: RobustScaler | EPS: 1.0 | Min-samples: 3.0 | Clusters: 27.0 | Bruit: 1074.0
4. Score: 1564.9762 | Cas: cas1 | Scaler: StandardScaler | EPS: 1.5 | Min-samples: 5.0 | Clusters: 2.0 | Bruit: 63.0
5. Score: 1536.4600 | Cas: cas1 | Scaler: StandardScaler | EPS: 1.5 | Min-samples: 7.0 | Clusters: 2.0 | Bruit: 82.0

================================================================================
TOP 5 MEILLEURS MODÈLES GLOBAUX
================================================================================

TOP 5 - Score Composite (silhouette 40% + davies-bouldin 30% + calinski-harabasz 30%):
1. Score: 0.9014 | Modèle: DBSCAN | Cas: cas1 | Scaler: RobustScaler | EPS: 1.5 | Min-samples: 3.0 | Clusters: 24.0
2. Score: 0.7051 | Modèle: KMeans | Cas: cas1 | Scaler: RobustScaler | K-clusters: 2.0
3. Score: 0.6733 | Modèle: KMeans | Cas: cas1 | Scaler: RobustScaler | K-clusters: 3.0
4. Score: 0.6701 | Modèle: KMeans | Cas: cas1 | Scaler: RobustScaler | K-clusters: 25.0
5. Score: 0.6641 | Modèle: KMeans | Cas: cas1 | Scaler: RobustScaler | K-clusters: 20.0

================================================================================
ANALYSE GLOBALE DES PARAMÈTRES INFLUENTS
================================================================================

INFLUENCE DU NOMBRE DE FEATURES:
- cas1 (7 features): Silhouette moyen = 0.3508 ± 0.3686
- cas2 (6 features): Silhouette moyen = 0.1688 ± 0.2503
- cas3 (5 features): Silhouette moyen = 0.1224 ± 0.2413

INFLUENCE DU TYPE DE SCALING:
- StandardScaler: Silhouette moyen = 0.1413 ± 0.3002
- MinMaxScaler: Silhouette moyen = 0.2524 ± 0.1099
- RobustScaler: Silhouette moyen = 0.3080 ± 0.3726

PERFORMANCE COMPARATIVE DES MODÈLES:
- KMeans: Sil=0.2897, DB=1.2758, CH=31099.55
- DBSCAN: Sil=0.1698, DB=0.7970, CH=41532.57

================================================================================
RECOMMANDATIONS POUR LE DÉPLOIEMENT
================================================================================

MEILLEUR MODÈLE RECOMMANDÉ:
- Modèle: DBSCAN
- Cas de features: cas1
- Préprocessing: RobustScaler
- Features utilisées: valence, energy, danceability, acousticness, tempo, loudness, instrumentalness
- EPS: 1.5
- Min samples: 3.0
- Clusters détectés: 24.0

CODE POUR LE DÉPLOIEMENT:
# Chargement et preprocessing
from sklearn.preprocessing import RobustScaler
from sklearn.cluster import DBSCAN

# Sélection des features
features = ['valence', 'energy', 'danceability', 'acousticness', 'tempo', 'loudness', 'instrumentalness']
X = df[features]

# Preprocessing
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

# Modèle
model = DBSCAN(eps=1.5, min_samples=3.0)
clusters = model.fit_predict(X_scaled)

# Score de qualité attendu: 0.8005

================================================================================
EXPLICATION DES MÉTRIQUES D'ÉVALUATION
================================================================================

1. SILHOUETTE SCORE:
   - Mesure la cohésion intra-cluster vs séparation inter-cluster
   - Valeurs entre -1 et 1, optimal proche de 1
   - Indique si les points sont bien assignés à leur cluster
   - Pénalise les clusters trop proches ou mal séparés

2. DAVIES-BOULDIN SCORE:
   - Mesure la similarité moyenne entre chaque cluster et son plus similaire
   - Plus la valeur est faible, meilleur est le clustering
   - Évalue la compacité intra-cluster et la séparation inter-cluster
   - Particulièrement sensible aux clusters de formes sphériques

3. CALINSKI-HARABASZ SCORE:
   - Ratio de la variance inter-cluster sur la variance intra-cluster
   - Plus la valeur est élevée, meilleur est le clustering
   - Favorise les clusters compacts et bien séparés
   - Aussi appelé Variance Ratio Criterion

================================================================================
CONSEILS D'UTILISATION EN PRODUCTION
================================================================================

1. PRÉPARATION DES DONNÉES:
   - Appliquer le même preprocessing que lors de l'entraînement
   - Vérifier la qualité des données d'entrée
   - Gérer les valeurs manquantes de manière cohérente

2. MONITORING:
   - Surveiller la distribution des clusters au fil du temps
   - Recalculer périodiquement les métriques sur de nouvelles données
   - Réentraîner le modèle si les performances se dégradent

3. INTERPRÉTATION:
   - Analyser les caractéristiques moyennes de chaque cluster
   - Créer des profils musicaux basés sur les clusters
   - Utiliser pour la recommandation ou la classification automatique

Résultats sauvegardés dans:
- resultats_clustering_complets.csv
- top5_meilleurs_modeles.csv

ANALYSE TERMINÉE AVEC SUCCÈS!

#### Résultats TOP 5

In [6]:


df_resultats_top_5 = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/top5_meilleurs_modeles.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_resultats_top_5

,cas,features_count,scaler,modele,k_clusters,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,features_list,eps,min_samples,n_clusters,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,cas1,7,RobustScaler,DBSCAN,NaN,0.800550,0.431446,3.472722e+06,5403,"valence, energy, danceability, acousticness, t...",1.5,3.0,24.0,780.0,0.884716,0.824887,1.000000,0.901352
1,cas1,7,RobustScaler,KMeans,2.0,0.961593,0.167324,5.910510e+04,5403,"valence, energy, danceability, acousticness, t...",NaN,NaN,NaN,NaN,1.000000,1.000000,0.017018,0.705106
2,cas1,7,RobustScaler,KMeans,3.0,0.952270,0.327891,9.098101e+04,5403,"valence, energy, danceability, acousticness, t...",NaN,NaN,NaN,NaN,0.993326,0.893544,0.026197,0.673253
3,cas1,7,RobustScaler,KMeans,25.0,0.868258,0.467364,6.545609e+05,5403,"valence, energy, danceability, acousticness, t...",NaN,NaN,NaN,NaN,0.933185,0.801073,0.188485,0.670141
4,cas1,7,RobustScaler,KMeans,20.0,0.901174,0.481162,5.070856e+05,5403,"valence, energy, danceability, acousticness, t...",NaN,NaN,NaN,NaN,0.956749,0.791925,0.146018,0.664082

### Version 2

In [7]:
# =============================================================================
# ANALYSE ML CLUSTERING MUSICAL - VERSION CORRIGÉE ET COMMENTÉE
# =============================================================================

# Imports standards - regroupés selon les bonnes pratiques PEP-8
import os  # Module pour les opérations système d'exploitation
import sys  # Module pour l'accès aux variables de l'interpréteur Python
import time  # Module pour la gestion du temps et des mesures de performance
import warnings  # Module pour la gestion des avertissements Python
import platform  # Module pour obtenir des informations sur la plateforme système
import subprocess  # Module pour l'exécution de commandes système
from datetime import datetime  # Classe pour la manipulation des dates et heures

# Imports tiers - bibliothèques externes installées via pip
import pandas as pd  # Bibliothèque pour la manipulation de données tabulaires
import numpy as np  # Bibliothèque pour le calcul numérique et les opérations sur arrays
import matplotlib.pyplot as plt  # Bibliothèque pour la création de graphiques
import seaborn as sns  # Bibliothèque pour la visualisation statistique avancée

# Imports scikit-learn - modules spécifiques pour le machine learning
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
# StandardScaler : normalisation z-score (moyenne=0, écart-type=1)
# MinMaxScaler : normalisation min-max (valeurs entre 0 et 1)
# RobustScaler : normalisation robuste utilisant médiane et IQR

from sklearn.cluster import KMeans, DBSCAN
# KMeans : algorithme de clustering par partition avec centroïdes
# DBSCAN : algorithme de clustering basé sur la densité

from sklearn.neighbors import NearestNeighbors
# NearestNeighbors : algorithme pour trouver les k plus proches voisins

from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
# silhouette_score : mesure la cohésion et séparation des clusters
# davies_bouldin_score : évalue la compacité et séparation des clusters
# calinski_harabasz_score : ratio de la variance inter/intra clusters

# Configuration des avertissements
warnings.filterwarnings('ignore')  # Supprime les messages d'avertissement pour un affichage plus propre

# Variables globales pour les dépendances optionnelles
TQDM_AVAILABLE = False  # Flag pour vérifier la disponibilité de tqdm
PDF_AVAILABLE = False   # Flag pour vérifier la disponibilité de fpdf

def installer_dependances():
    """
    Installe et importe les dépendances optionnelles (tqdm et fpdf).
    
    Cette fonction gère l'installation automatique des packages optionnels
    nécessaires pour les barres de progression et la génération PDF.
    
    Returns:
        tuple: (TQDM_AVAILABLE, PDF_AVAILABLE) - statut des dépendances
    """
    global TQDM_AVAILABLE, PDF_AVAILABLE  # Déclaration des variables globales à modifier
    
    # Installation et import de tqdm pour les barres de progression
    try:
        from tqdm import tqdm  # Tentative d'import direct
        TQDM_AVAILABLE = True
        print("✓ tqdm disponible pour barres de progression")
    except ImportError:  # Exception levée si le module n'est pas installé
        print("Installation de tqdm en cours...")
        try:
            # subprocess.check_call exécute une commande système et vérifie le code retour
            subprocess.check_call([sys.executable, "-m", "pip", "install", "tqdm"])
            from tqdm import tqdm  # Nouvel essai d'import après installation
            TQDM_AVAILABLE = True
            print("✓ tqdm installé et importé avec succès!")
        except Exception as e:  # Capture toute exception durant l'installation
            print(f"Impossible d'installer tqdm: {e}")
            TQDM_AVAILABLE = False
    
    # Installation et import de fpdf2 pour la génération PDF
    try:
        from fpdf import FPDF  # Tentative d'import direct
        PDF_AVAILABLE = True
        print("✓ fpdf2 disponible pour génération PDF")
    except ImportError:
        print("Installation de fpdf2 en cours...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "fpdf2"])
            from fpdf import FPDF
            PDF_AVAILABLE = True
            print("✓ fpdf2 installé avec succès!")
        except Exception as e:
            print(f"Impossible d'installer fpdf2: {e}")
            PDF_AVAILABLE = False
    
    return TQDM_AVAILABLE, PDF_AVAILABLE

def charger_donnees_spotify():
    """
    Charge les données Spotify depuis le fichier CSV avec gestion multi-OS.
    
    Cette fonction détecte automatiquement le système d'exploitation et
    teste plusieurs chemins possibles pour localiser le fichier de données.
    
    Returns:
        pd.DataFrame: DataFrame contenant les données Spotify
        
    Raises:
        FileNotFoundError: Si aucun fichier n'est trouvé dans les chemins testés
    """
    # Détection du système d'exploitation
    system = platform.system()  # Retourne 'Windows', 'Darwin' (macOS), ou 'Linux'
    
    # Liste des chemins possibles selon l'OS et la structure du projet
    chemins_possibles = [
        # Chemins relatifs (plus portables)
        "./Datasets/df_concat_tagged.csv",           # Dossier Datasets dans le répertoire courant
        "./df_concat_tagged.csv",                    # Fichier dans le répertoire courant
        "df_concat_tagged.csv",                      # Fichier dans le répertoire courant (nom seul)
        "../Datasets/df_concat_tagged.csv",          # Dossier Datasets au niveau parent
        
        # Chemins absolus spécifiques (fallback)
        "/Users/bertranddevulder/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_et_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/df_concat_tagged.csv",
        r"C:\Users\beber\Documents\Cours\Wild_Code_School\Semaine_8_Visualisation_interactive_&_Pandas_approfondi\Projet_2\Projet_2_local\Datasets\df_concat_tagged.csv"
    ]
    
    # Tentative de chargement avec chaque chemin
    for chemin in chemins_possibles:
        try:
            # pd.read_csv lit un fichier CSV et retourne un DataFrame
            df_spotify = pd.read_csv(chemin)
            print(f"✓ Données chargées avec succès depuis: {chemin}")
            print(f"✓ Forme du DataFrame: {df_spotify.shape}")  # (nombre_lignes, nombre_colonnes)
            return df_spotify
        except FileNotFoundError:
            # Continue avec le chemin suivant si le fichier n'est pas trouvé
            continue
        except Exception as e:
            # Affiche les erreurs non liées aux fichiers manquants
            print(f"Erreur lors du chargement de {chemin}: {e}")
            continue
    
    # Lève une exception si aucun fichier n'a pu être chargé
    raise FileNotFoundError("❌ Impossible de trouver le fichier df_concat_tagged.csv dans les chemins testés")

def definir_cas_features():
    """
    Définit les trois cas de features selon les spécifications du projet.
    
    Cette fonction centralise la définition des différents ensembles de
    caractéristiques audio à tester pour le clustering.
    
    Returns:
        dict: Dictionnaire avec les trois cas de features
    """
    # Cas 1: Ensemble complet avec 7 features (le plus riche en information)
    features_cas1 = [
        'valence',          # Valence émotionnelle (0=triste, 1=joyeux)
        'energy',           # Énergie perçue (0=calme, 1=énergique)
        'danceability',     # Capacité à danser (0=difficile, 1=facile)
        'acousticness',     # Caractère acoustique (0=électronique, 1=acoustique)
        'tempo',            # Tempo en BPM (battements par minute)
        'loudness',         # Volume sonore en décibels
        'instrumentalness'  # Caractère instrumental (0=vocal, 1=instrumental)
    ]
    
    # Cas 2: Ensemble réduit sans instrumentalness (6 features)
    features_cas2 = [
        'valence',
        'energy', 
        'danceability',
        'acousticness',
        'tempo',
        'loudness'
    ]
    
    # Cas 3: Ensemble minimal avec features principales (5 features)
    features_cas3 = [
        'valence',
        'energy',
        'danceability', 
        'acousticness',
        'tempo'
    ]
    
    return {
        'cas1': features_cas1,
        'cas2': features_cas2,
        'cas3': features_cas3
    }

def nettoyer_donnees(X):
    """
    Nettoie les données en supprimant les valeurs manquantes et infinies.
    
    Args:
        X (pd.DataFrame): DataFrame avec les features à nettoyer
        
    Returns:
        pd.DataFrame: DataFrame nettoyé
    """
    print(f"   🧹 Nettoyage données: {len(X):,} lignes avant nettoyage")
    
    # Suppression des lignes avec valeurs manquantes (NaN)
    X_clean = X.dropna()
    
    # Remplacement des valeurs infinies par NaN puis suppression
    X_clean = X_clean.replace([np.inf, -np.inf], np.nan).dropna()
    
    print(f"   ✅ Données nettoyées: {len(X_clean):,} lignes après nettoyage")
    
    # Vérification qu'il reste suffisamment de données pour l'analyse
    if len(X_clean) < 100:
        print(f"   ⚠️ Attention: Seulement {len(X_clean)} échantillons restants")
    
    return X_clean

def tester_configuration_clustering(X_scaled, modele_type, **params):
    """
    Teste une configuration de clustering et calcule les métriques.
    
    Args:
        X_scaled (np.array): Données préprocessées
        modele_type (str): 'KMeans' ou 'DBSCAN'
        **params: Paramètres spécifiques au modèle
        
    Returns:
        dict: Résultats avec métriques ou None si échec
    """
    try:
        debut_test = time.time()  # Début du chronométrage
        
        if modele_type == 'KMeans':
            # Création et entraînement du modèle K-means
            # n_clusters: nombre de clusters à former
            # random_state=42: graine aléatoire pour reproductibilité
            # n_init=10: nombre d'initialisations différentes à tester
            modele = KMeans(
                n_clusters=params['k_clusters'],
                random_state=42,
                n_init=10
            )
            labels = modele.fit_predict(X_scaled)  # Entraînement et prédiction en une étape
            
        elif modele_type == 'DBSCAN':
            # Création et entraînement du modèle DBSCAN
            # eps: distance maximale entre points d'un même cluster
            # min_samples: nombre minimum de points pour former un cluster dense
            modele = DBSCAN(
                eps=params['eps'],
                min_samples=params['min_samples']
            )
            labels = modele.fit_predict(X_scaled)
            
            # Calcul du nombre de clusters détectés (excluant le bruit=-1)
            n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
            if n_clusters < 2:  # Au moins 2 clusters nécessaires pour les métriques
                return None
            
            # Filtrage du bruit pour le calcul des métriques
            mask_no_noise = labels != -1  # Masque pour exclure les points de bruit
            if np.sum(mask_no_noise) < 10:  # Vérification qu'il reste assez de points
                return None
                
            X_scaled = X_scaled[mask_no_noise]  # Application du filtre
            labels = labels[mask_no_noise]
        
        # Vérification du nombre de clusters uniques
        n_clusters_unique = len(np.unique(labels))
        if n_clusters_unique < 2:
            return None
        
        # Calcul des métriques d'évaluation
        # Silhouette Score: mesure la qualité des clusters (-1 à 1, plus élevé = meilleur)
        sil_score = silhouette_score(X_scaled, labels)
        
        # Davies-Bouldin Score: mesure la compacité/séparation (0 à ∞, plus bas = meilleur)
        db_score = davies_bouldin_score(X_scaled, labels)
        
        # Calinski-Harabasz Score: ratio variance inter/intra (0 à ∞, plus élevé = meilleur)
        ch_score = calinski_harabasz_score(X_scaled, labels)
        
        duree_test = time.time() - debut_test  # Calcul du temps d'exécution
        
        # Construction du dictionnaire de résultats
        resultats = {
            'silhouette_score': sil_score,
            'davies_bouldin_score': db_score,
            'calinski_harabasz_score': ch_score,
            'n_samples': len(X_scaled),
            'duree_calcul_sec': duree_test,
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        
        # Ajout des paramètres spécifiques au modèle
        if modele_type == 'DBSCAN':
            resultats.update({
                'n_clusters_detectes': n_clusters,
                'noise_points': np.sum(labels == -1) if modele_type == 'DBSCAN' else 0
            })
        
        return resultats
        
    except Exception as e:
        # Gestion silencieuse des erreurs pour éviter d'interrompre le processus global
        return None

def analyser_clustering_complet(df_spotify):
    """
    Effectue l'analyse complète de clustering avec tous les paramètres.
    
    Args:
        df_spotify (pd.DataFrame): DataFrame Spotify complet
        
    Returns:
        list: Liste des résultats de tous les tests
    """
    print("🎵 DÉBUT DE L'ANALYSE CLUSTERING MUSICAL")
    print(f"📊 Données chargées: {df_spotify.shape[0]:,} lignes, {df_spotify.shape[1]} colonnes")
    
    # Définition des paramètres d'expérimentation
    cases_features = definir_cas_features()
    
    # Scalers pour la normalisation des données
    scalers = {
        'StandardScaler': StandardScaler(),    # Normalisation z-score
        'MinMaxScaler': MinMaxScaler(),        # Normalisation min-max
        'RobustScaler': RobustScaler()         # Normalisation robuste
    }
    
    # Paramètres pour les algorithmes de clustering
    kmeans_k_values = [2, 3, 4, 5, 7, 10, 15, 20, 25]    # Nombres de clusters à tester
    eps_values = [0.3, 0.5, 0.7, 1.0, 1.5]               # Valeurs epsilon pour DBSCAN
    min_samples_values = [3, 5, 7, 10]                    # Valeurs min_samples pour DBSCAN
    
    resultats = []  # Liste pour stocker tous les résultats
    debut_temps_total = time.time()
    
    # Boucle principale sur les cas de features
    for cas_nom, features in cases_features.items():
        print(f"\n🎯 TRAITEMENT {cas_nom.upper()} - {len(features)} features")
        
        # Vérification de la disponibilité des features
        features_disponibles = [f for f in features if f in df_spotify.columns]
        if len(features_disponibles) != len(features):
            features_manquantes = set(features) - set(features_disponibles)
            print(f"   ❌ Features manquantes: {features_manquantes}")
            continue
        
        # Extraction et nettoyage des données
        X = df_spotify[features_disponibles].copy()
        X_clean = nettoyer_donnees(X)
        
        if len(X_clean) < 100:
            print(f"   ❌ Pas assez de données après nettoyage: {len(X_clean)} lignes")
            continue
        
        # Test avec chaque scaler
        for scaler_nom, scaler in scalers.items():
            print(f"   🔧 Preprocessing avec {scaler_nom}")
            
            try:
                # Application du scaler
                # fit calcule les paramètres de normalisation (moyenne, écart-type, etc.)
                # transform applique la normalisation aux données
                X_scaled = scaler.fit_transform(X_clean)
                
                # Tests K-means avec différents nombres de clusters
                for k_clusters in kmeans_k_values:
                    if k_clusters > len(X_scaled):  # Éviter k > nombre d'échantillons
                        continue
                    
                    # Test de la configuration K-means
                    resultats_test = tester_configuration_clustering(
                        X_scaled, 'KMeans', k_clusters=k_clusters
                    )
                    
                    if resultats_test is not None:
                        # Ajout des métadonnées à chaque résultat
                        resultats_test.update({
                            'cas': cas_nom,
                            'features_count': len(features_disponibles),
                            'features_list': ', '.join(features_disponibles),
                            'scaler': scaler_nom,
                            'modele_clustering': 'KMeans',
                            'k_clusters': k_clusters,
                            'eps': None,
                            'min_samples': None
                        })
                        resultats.append(resultats_test)
                
                # Tests DBSCAN avec différents paramètres
                for eps in eps_values:
                    for min_samples in min_samples_values:
                        # Test de la configuration DBSCAN
                        resultats_test = tester_configuration_clustering(
                            X_scaled, 'DBSCAN', eps=eps, min_samples=min_samples
                        )
                        
                        if resultats_test is not None:
                            resultats_test.update({
                                'cas': cas_nom,
                                'features_count': len(features_disponibles),
                                'features_list': ', '.join(features_disponibles),
                                'scaler': scaler_nom,
                                'modele_clustering': 'DBSCAN',
                                'k_clusters': None,
                                'eps': eps,
                                'min_samples': min_samples
                            })
                            resultats.append(resultats_test)
                            
            except Exception as e:
                print(f"   ❌ Erreur avec {scaler_nom}: {str(e)}")
                continue
    
    # Statistiques finales
    duree_totale = time.time() - debut_temps_total
    print(f"\n🏁 TESTS TERMINÉS:")
    print(f"   • Configurations testées: {len(resultats):,}")
    print(f"   • Durée totale: {duree_totale:.1f}s ({duree_totale/60:.1f} min)")
    
    return resultats

def analyser_resultats(resultats):
    """
    Analyse les résultats et identifie les meilleures configurations.
    
    Args:
        resultats (list): Liste des résultats de tous les tests
        
    Returns:
        dict: Analyses et recommandations
    """
    if not resultats:
        print("❌ Aucun résultat à analyser")
        return {}
    
    print(f"\n📊 ANALYSE DES RÉSULTATS - {len(resultats):,} configurations")
    
    # Conversion en DataFrame pour faciliter l'analyse
    df_resultats = pd.DataFrame(resultats)
    
    # Calcul d'un score composite normalisé
    # Normalisation de chaque métrique entre 0 et 1
    min_sil = df_resultats['silhouette_score'].min()
    max_sil = df_resultats['silhouette_score'].max()
    df_resultats['sil_norm'] = (df_resultats['silhouette_score'] - min_sil) / (max_sil - min_sil)
    
    # Davies-Bouldin: plus bas = meilleur, donc inversion de l'échelle
    min_db = df_resultats['davies_bouldin_score'].min()
    max_db = df_resultats['davies_bouldin_score'].max()
    df_resultats['db_norm'] = 1 - ((df_resultats['davies_bouldin_score'] - min_db) / (max_db - min_db))
    
    min_ch = df_resultats['calinski_harabasz_score'].min()
    max_ch = df_resultats['calinski_harabasz_score'].max()
    df_resultats['ch_norm'] = (df_resultats['calinski_harabasz_score'] - min_ch) / (max_ch - min_ch)
    
    # Score composite pondéré (40% Silhouette + 30% Davies-Bouldin + 30% Calinski-Harabasz)
    df_resultats['score_composite'] = (
        df_resultats['sil_norm'] * 0.4 + 
        df_resultats['db_norm'] * 0.3 + 
        df_resultats['ch_norm'] * 0.3
    )
    
    # Identification du TOP 5
    top5_global = df_resultats.nlargest(5, 'score_composite')
    
    print(f"\n🏆 TOP 5 MEILLEURES CONFIGURATIONS:")
    print("="*80)
    
    for idx, (_, row) in enumerate(top5_global.iterrows(), 1):
        print(f"\n🥇 RANG #{idx}")
        print(f"   Modèle: {row['modele_clustering']}")
        if row['modele_clustering'] == 'KMeans':
            print(f"   Paramètres: k_clusters={row['k_clusters']}")
        else:
            print(f"   Paramètres: eps={row['eps']}, min_samples={row['min_samples']}")
        print(f"   Cas features: {row['cas']} ({row['features_count']} features)")
        print(f"   Scaler: {row['scaler']}")
        print(f"   Score composite: {row['score_composite']:.4f}")
        print(f"   Silhouette: {row['silhouette_score']:.4f}")
        print(f"   Davies-Bouldin: {row['davies_bouldin_score']:.4f}")
        print(f"   Calinski-Harabasz: {row['calinski_harabasz_score']:.2f}")
    
    # Sauvegarde des résultats
    try:
        df_resultats.to_csv('resultats_clustering_complets.csv', index=False)
        top5_global.to_csv('top5_configurations.csv', index=False)
        print(f"\n💾 Fichiers sauvegardés:")
        print(f"   • resultats_clustering_complets.csv")
        print(f"   • top5_configurations.csv")
    except Exception as e:
        print(f"❌ Erreur lors de la sauvegarde: {e}")
    
    return {
        'tous_resultats': df_resultats,
        'top5_global': top5_global,
        'meilleur_modele': top5_global.iloc[0]
    }

def main():
    """
    Fonction principale qui orchestre l'analyse complète.
    """
    print("🚀 LANCEMENT DE L'ANALYSE ML CLUSTERING MUSICAL")
    print(f"⏰ Début: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # Installation des dépendances optionnelles
        installer_dependances()
        
        # Chargement des données
        df_spotify = charger_donnees_spotify()
        
        # Analyse complète
        resultats = analyser_clustering_complet(df_spotify)
        
        # Analyse des résultats
        analyses = analyser_resultats(resultats)
        
        print(f"\n🎉 ANALYSE TERMINÉE AVEC SUCCÈS!")
        print(f"⏰ Fin: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        return analyses
        
    except Exception as e:
        print(f"❌ ERREUR: {e}")
        import traceback
        traceback.print_exc()
        return None

# Point d'entrée du script
if __name__ == "__main__":
    resultats_finaux = main()

🚀 LANCEMENT DE L'ANALYSE ML CLUSTERING MUSICAL
⏰ Début: 2025-06-24 11:19:50
✓ tqdm disponible pour barres de progression
✓ fpdf2 disponible pour génération PDF
✓ Données chargées avec succès depuis: ../Datasets/df_concat_tagged.csv
✓ Forme du DataFrame: (5403, 18)
🎵 DÉBUT DE L'ANALYSE CLUSTERING MUSICAL
📊 Données chargées: 5,403 lignes, 18 colonnes

🎯 TRAITEMENT CAS1 - 7 features
   🧹 Nettoyage données: 5,403 lignes avant nettoyage
   ✅ Données nettoyées: 5,403 lignes après nettoyage
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🎯 TRAITEMENT CAS2 - 6 features
   🧹 Nettoyage données: 5,403 lignes avant nettoyage
   ✅ Données nettoyées: 5,403 lignes après nettoyage
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🎯 TRAITEMENT CAS3 - 5 features
   🧹 Nettoyage données: 5,403 lignes avant nettoyage
   ✅ Données nettoyées: 5,403 lignes après nettoyage
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🏁 TESTS TERMINÉS:
   • Configurations testées: 166
   • Durée totale: 367.5s (6.1 min)

📊 ANALYSE DES RÉSULTATS - 166 configurations

🏆 TOP 5 MEILLEURES CONFIGURATIONS:
================================================================================

🥇 RANG #1
   Modèle: DBSCAN
   Paramètres: eps=1.5, min_samples=3.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.9014
   Silhouette: 0.8005
   Davies-Bouldin: 0.4314
   Calinski-Harabasz: 3472722.33

🥇 RANG #2
   Modèle: KMeans
   Paramètres: k_clusters=2.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.7051
   Silhouette: 0.9616
   Davies-Bouldin: 0.1673
   Calinski-Harabasz: 59105.10

🥇 RANG #3
   Modèle: KMeans
   Paramètres: k_clusters=3.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6733
   Silhouette: 0.9523
   Davies-Bouldin: 0.3279
   Calinski-Harabasz: 90981.01

🥇 RANG #4
   Modèle: KMeans
   Paramètres: k_clusters=25.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6701
   Silhouette: 0.8683
   Davies-Bouldin: 0.4674
   Calinski-Harabasz: 654560.92

🥇 RANG #5
   Modèle: KMeans
   Paramètres: k_clusters=20.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6641
   Silhouette: 0.9012
   Davies-Bouldin: 0.4812
   Calinski-Harabasz: 507085.60

💾 Fichiers sauvegardés:
   • resultats_clustering_complets.csv
   • top5_configurations.csv

🎉 ANALYSE TERMINÉE AVEC SUCCÈS!
⏰ Fin: 2025-06-24 11:26:02

#### Résultats

##### Résultats globaux

In [8]:
df_resultats_globaux = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/resultats_clustering_complets.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_resultats_globaux

,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,duree_calcul_sec,timestamp,cas,features_count,features_list,scaler,modele_clustering,k_clusters,eps,min_samples,n_clusters_detectes,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,0.342094,1.347416,2118.826048,5403,1.828225,2025-06-24 11:19:56,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,2.0,NaN,NaN,NaN,NaN,0.556528,0.217596,6.086347e-04,0.288073
1,0.276683,1.230408,1986.473428,5403,1.941960,2025-06-24 11:19:58,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,3.0,NaN,NaN,NaN,NaN,0.509703,0.295173,5.705225e-04,0.292604
2,0.198888,1.501536,1787.099613,5403,2.496860,2025-06-24 11:20:01,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,4.0,NaN,NaN,NaN,NaN,0.454013,0.115415,5.131111e-04,0.216384
3,0.193390,1.404206,1655.312477,5403,0.988804,2025-06-24 11:20:02,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,5.0,NaN,NaN,NaN,NaN,0.450078,0.179945,4.751618e-04,0.234157
4,0.190992,1.326393,1450.366250,5403,1.380546,2025-06-24 11:20:03,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,7.0,NaN,NaN,NaN,NaN,0.448361,0.231535,4.161457e-04,0.248930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,-0.133542,1.193926,78.603442,1054,0.158585,2025-06-24 11:25:51,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.3,10.0,25.0,0.0,0.216041,0.319361,2.113429e-05,0.182231
162,-0.230535,0.846615,8.058357,5232,1.235486,2025-06-24 11:25:53,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,3.0,14.0,0.0,0.146608,0.549629,8.202005e-07,0.223532
163,0.185849,0.612405,16.484363,5136,0.964857,2025-06-24 11:25:54,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,5.0,4.0,0.0,0.444679,0.704910,3.246544e-06,0.389346
164,-0.071282,0.917260,23.791211,5049,0.875791,2025-06-24 11:25:55,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,7.0,5.0,0.0,0.260610,0.502791,5.350617e-06,0.255083
165,0.400192,0.530824,48.623634,4912,0.584195,2025-06-24 11:25:55,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,10.0,2.0,0.0,0.598117,0.758999,1.250134e-05,0.466950

##### Top 5 configurations

In [9]:
df_Top_5_configurations = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/top5_configurations.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_Top_5_configurations

,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,duree_calcul_sec,timestamp,cas,features_count,features_list,scaler,modele_clustering,k_clusters,eps,min_samples,n_clusters_detectes,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,0.800550,0.431446,3.472722e+06,4623,2.090372,2025-06-24 11:22:11,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,1.5,3.0,24.0,0.0,0.884716,0.824887,1.000000,0.901352
1,0.961593,0.167324,5.910510e+04,5403,0.836703,2025-06-24 11:21:47,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,2.0,NaN,NaN,NaN,NaN,1.000000,1.000000,0.017018,0.705106
2,0.952270,0.327891,9.098101e+04,5403,1.265262,2025-06-24 11:21:48,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,3.0,NaN,NaN,NaN,NaN,0.993326,0.893544,0.026197,0.673253
3,0.868258,0.467364,6.545609e+05,5403,2.368792,2025-06-24 11:21:59,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,25.0,NaN,NaN,NaN,NaN,0.933185,0.801073,0.188485,0.670141
4,0.901174,0.481162,5.070856e+05,5403,1.459780,2025-06-24 11:21:57,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,20.0,NaN,NaN,NaN,NaN,0.956749,0.791925,0.146018,0.664082

## Tests NN + K-means et DBSCAN (différentes configuration), avec génération pdf

### Version 1

In [10]:
# =============================================================================
# ANALYSE ML CLUSTERING MUSICAL - VERSION CORRIGÉE ET COMMENTÉE
# =============================================================================

# Imports standards - regroupés selon les bonnes pratiques PEP-8
import os  # Module pour les opérations système d'exploitation
import sys  # Module pour l'accès aux variables de l'interpréteur Python
import time  # Module pour la gestion du temps et des mesures de performance
import warnings  # Module pour la gestion des avertissements Python
import platform  # Module pour obtenir des informations sur la plateforme système
import subprocess  # Module pour l'exécution de commandes système
from datetime import datetime  # Classe pour la manipulation des dates et heures

# Imports tiers - bibliothèques externes installées via pip
import pandas as pd  # Bibliothèque pour la manipulation de données tabulaires
import numpy as np  # Bibliothèque pour le calcul numérique et les opérations sur arrays
import matplotlib.pyplot as plt  # Bibliothèque pour la création de graphiques
import seaborn as sns  # Bibliothèque pour la visualisation statistique avancée

# Imports scikit-learn - modules spécifiques pour le machine learning
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
# StandardScaler : normalisation z-score (moyenne=0, écart-type=1)
# MinMaxScaler : normalisation min-max (valeurs entre 0 et 1)
# RobustScaler : normalisation robuste utilisant médiane et IQR

from sklearn.cluster import KMeans, DBSCAN
# KMeans : algorithme de clustering par partition avec centroïdes
# DBSCAN : algorithme de clustering basé sur la densité

from sklearn.neighbors import NearestNeighbors
# NearestNeighbors : algorithme pour trouver les k plus proches voisins

from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
# silhouette_score : mesure la cohésion et séparation des clusters
# davies_bouldin_score : évalue la compacité et séparation des clusters
# calinski_harabasz_score : ratio de la variance inter/intra clusters

# Configuration des avertissements
warnings.filterwarnings('ignore')  # Supprime les messages d'avertissement pour un affichage plus propre

# Variables globales pour les dépendances optionnelles
TQDM_AVAILABLE = False  # Flag pour vérifier la disponibilité de tqdm
PDF_AVAILABLE = False   # Flag pour vérifier la disponibilité de fpdf

def installer_dependances():
    """
    Installe et importe les dépendances optionnelles (tqdm et fpdf).
    
    Cette fonction gère l'installation automatique des packages optionnels
    nécessaires pour les barres de progression et la génération PDF.
    
    Returns:
        tuple: (TQDM_AVAILABLE, PDF_AVAILABLE) - statut des dépendances
    """
    global TQDM_AVAILABLE, PDF_AVAILABLE  # Déclaration des variables globales à modifier
    
    # Installation et import de tqdm pour les barres de progression
    try:
        from tqdm import tqdm  # Tentative d'import direct
        TQDM_AVAILABLE = True
        print("✓ tqdm disponible pour barres de progression")
    except ImportError:  # Exception levée si le module n'est pas installé
        print("Installation de tqdm en cours...")
        try:
            # subprocess.check_call exécute une commande système et vérifie le code retour
            subprocess.check_call([sys.executable, "-m", "pip", "install", "tqdm"])
            from tqdm import tqdm  # Nouvel essai d'import après installation
            TQDM_AVAILABLE = True
            print("✓ tqdm installé et importé avec succès!")
        except Exception as e:  # Capture toute exception durant l'installation
            print(f"Impossible d'installer tqdm: {e}")
            TQDM_AVAILABLE = False
    
    # Installation et import de fpdf2 pour la génération PDF
    try:
        from fpdf import FPDF  # Tentative d'import direct
        PDF_AVAILABLE = True
        print("✓ fpdf2 disponible pour génération PDF")
    except ImportError:
        print("Installation de fpdf2 en cours...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "fpdf2"])
            from fpdf import FPDF
            PDF_AVAILABLE = True
            print("✓ fpdf2 installé avec succès!")
        except Exception as e:
            print(f"Impossible d'installer fpdf2: {e}")
            PDF_AVAILABLE = False
    
    return TQDM_AVAILABLE, PDF_AVAILABLE

def charger_donnees_spotify():
    """
    Charge les données Spotify depuis le fichier CSV avec gestion multi-OS.
    
    Cette fonction détecte automatiquement le système d'exploitation et
    teste plusieurs chemins possibles pour localiser le fichier de données.
    
    Returns:
        pd.DataFrame: DataFrame contenant les données Spotify
        
    Raises:
        FileNotFoundError: Si aucun fichier n'est trouvé dans les chemins testés
    """
    # Détection du système d'exploitation
    system = platform.system()  # Retourne 'Windows', 'Darwin' (macOS), ou 'Linux'
    
    # Liste des chemins possibles selon l'OS et la structure du projet
    chemins_possibles = [
        # Chemins relatifs (plus portables)
        "./Datasets/df_concat_tagged.csv",           # Dossier Datasets dans le répertoire courant
        "./df_concat_tagged.csv",                    # Fichier dans le répertoire courant
        "df_concat_tagged.csv",                      # Fichier dans le répertoire courant (nom seul)
        "../Datasets/df_concat_tagged.csv",          # Dossier Datasets au niveau parent
        
        # Chemins absolus spécifiques (fallback)
        "/Users/bertranddevulder/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_et_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/df_concat_tagged.csv",
        r"C:\Users\beber\Documents\Cours\Wild_Code_School\Semaine_8_Visualisation_interactive_&_Pandas_approfondi\Projet_2\Projet_2_local\Datasets\df_concat_tagged.csv"
    ]
    
    # Tentative de chargement avec chaque chemin
    for chemin in chemins_possibles:
        try:
            # pd.read_csv lit un fichier CSV et retourne un DataFrame
            df_spotify = pd.read_csv(chemin)
            print(f"✓ Données chargées avec succès depuis: {chemin}")
            print(f"✓ Forme du DataFrame: {df_spotify.shape}")  # (nombre_lignes, nombre_colonnes)
            return df_spotify
        except FileNotFoundError:
            # Continue avec le chemin suivant si le fichier n'est pas trouvé
            continue
        except Exception as e:
            # Affiche les erreurs non liées aux fichiers manquants
            print(f"Erreur lors du chargement de {chemin}: {e}")
            continue
    
    # Lève une exception si aucun fichier n'a pu être chargé
    raise FileNotFoundError("❌ Impossible de trouver le fichier df_concat_tagged.csv dans les chemins testés")

def definir_cas_features():
    """
    Définit les trois cas de features selon les spécifications du projet.
    
    Cette fonction centralise la définition des différents ensembles de
    caractéristiques audio à tester pour le clustering.
    
    Returns:
        dict: Dictionnaire avec les trois cas de features
    """
    # Cas 1: Ensemble complet avec 7 features (le plus riche en information)
    features_cas1 = [
        'valence',          # Valence émotionnelle (0=triste, 1=joyeux)
        'energy',           # Énergie perçue (0=calme, 1=énergique)
        'danceability',     # Capacité à danser (0=difficile, 1=facile)
        'acousticness',     # Caractère acoustique (0=électronique, 1=acoustique)
        'tempo',            # Tempo en BPM (battements par minute)
        'loudness',         # Volume sonore en décibels
        'instrumentalness'  # Caractère instrumental (0=vocal, 1=instrumental)
    ]
    
    # Cas 2: Ensemble réduit sans instrumentalness (6 features)
    features_cas2 = [
        'valence',
        'energy', 
        'danceability',
        'acousticness',
        'tempo',
        'loudness'
    ]
    
    # Cas 3: Ensemble minimal avec features principales (5 features)
    features_cas3 = [
        'valence',
        'energy',
        'danceability', 
        'acousticness',
        'tempo'
    ]
    
    return {
        'cas1': features_cas1,
        'cas2': features_cas2,
        'cas3': features_cas3
    }

def nettoyer_donnees(X):
    """
    Nettoie les données en supprimant les valeurs manquantes et infinies.
    
    Args:
        X (pd.DataFrame): DataFrame avec les features à nettoyer
        
    Returns:
        pd.DataFrame: DataFrame nettoyé
    """
    print(f"   🧹 Nettoyage données: {len(X):,} lignes avant nettoyage")
    
    # Suppression des lignes avec valeurs manquantes (NaN)
    X_clean = X.dropna()
    
    # Remplacement des valeurs infinies par NaN puis suppression
    X_clean = X_clean.replace([np.inf, -np.inf], np.nan).dropna()
    
    print(f"   ✅ Données nettoyées: {len(X_clean):,} lignes après nettoyage")
    
    # Vérification qu'il reste suffisamment de données pour l'analyse
    if len(X_clean) < 100:
        print(f"   ⚠️ Attention: Seulement {len(X_clean)} échantillons restants")
    
    return X_clean

def tester_configuration_clustering(X_scaled, modele_type, **params):
    """
    Teste une configuration de clustering et calcule les métriques.
    
    Args:
        X_scaled (np.array): Données préprocessées
        modele_type (str): 'KMeans' ou 'DBSCAN'
        **params: Paramètres spécifiques au modèle
        
    Returns:
        dict: Résultats avec métriques ou None si échec
    """
    try:
        debut_test = time.time()  # Début du chronométrage
        
        if modele_type == 'KMeans':
            # Création et entraînement du modèle K-means
            # n_clusters: nombre de clusters à former
            # random_state=42: graine aléatoire pour reproductibilité
            # n_init=10: nombre d'initialisations différentes à tester
            modele = KMeans(
                n_clusters=params['k_clusters'],
                random_state=42,
                n_init=10
            )
            labels = modele.fit_predict(X_scaled)  # Entraînement et prédiction en une étape
            
        elif modele_type == 'DBSCAN':
            # Création et entraînement du modèle DBSCAN
            # eps: distance maximale entre points d'un même cluster
            # min_samples: nombre minimum de points pour former un cluster dense
            modele = DBSCAN(
                eps=params['eps'],
                min_samples=params['min_samples']
            )
            labels = modele.fit_predict(X_scaled)
            
            # Calcul du nombre de clusters détectés (excluant le bruit=-1)
            n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
            if n_clusters < 2:  # Au moins 2 clusters nécessaires pour les métriques
                return None
            
            # Filtrage du bruit pour le calcul des métriques
            mask_no_noise = labels != -1  # Masque pour exclure les points de bruit
            if np.sum(mask_no_noise) < 10:  # Vérification qu'il reste assez de points
                return None
                
            X_scaled = X_scaled[mask_no_noise]  # Application du filtre
            labels = labels[mask_no_noise]
        
        # Vérification du nombre de clusters uniques
        n_clusters_unique = len(np.unique(labels))
        if n_clusters_unique < 2:
            return None
        
        # Calcul des métriques d'évaluation
        # Silhouette Score: mesure la qualité des clusters (-1 à 1, plus élevé = meilleur)
        sil_score = silhouette_score(X_scaled, labels)
        
        # Davies-Bouldin Score: mesure la compacité/séparation (0 à ∞, plus bas = meilleur)
        db_score = davies_bouldin_score(X_scaled, labels)
        
        # Calinski-Harabasz Score: ratio variance inter/intra (0 à ∞, plus élevé = meilleur)
        ch_score = calinski_harabasz_score(X_scaled, labels)
        
        duree_test = time.time() - debut_test  # Calcul du temps d'exécution
        
        # Construction du dictionnaire de résultats
        resultats = {
            'silhouette_score': sil_score,
            'davies_bouldin_score': db_score,
            'calinski_harabasz_score': ch_score,
            'n_samples': len(X_scaled),
            'duree_calcul_sec': duree_test,
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        
        # Ajout des paramètres spécifiques au modèle
        if modele_type == 'DBSCAN':
            resultats.update({
                'n_clusters_detectes': n_clusters,
                'noise_points': np.sum(labels == -1) if modele_type == 'DBSCAN' else 0
            })
        
        return resultats
        
    except Exception as e:
        # Gestion silencieuse des erreurs pour éviter d'interrompre le processus global
        return None

def analyser_clustering_complet(df_spotify):
    """
    Effectue l'analyse complète de clustering avec tous les paramètres.
    
    Args:
        df_spotify (pd.DataFrame): DataFrame Spotify complet
        
    Returns:
        list: Liste des résultats de tous les tests
    """
    print("🎵 DÉBUT DE L'ANALYSE CLUSTERING MUSICAL")
    print(f"📊 Données chargées: {df_spotify.shape[0]:,} lignes, {df_spotify.shape[1]} colonnes")
    
    # Définition des paramètres d'expérimentation
    cases_features = definir_cas_features()
    
    # Scalers pour la normalisation des données
    scalers = {
        'StandardScaler': StandardScaler(),    # Normalisation z-score
        'MinMaxScaler': MinMaxScaler(),        # Normalisation min-max
        'RobustScaler': RobustScaler()         # Normalisation robuste
    }
    
    # Paramètres pour les algorithmes de clustering
    kmeans_k_values = [2, 3, 4, 5, 7, 10, 15, 20, 25]    # Nombres de clusters à tester
    eps_values = [0.3, 0.5, 0.7, 1.0, 1.5]               # Valeurs epsilon pour DBSCAN
    min_samples_values = [3, 5, 7, 10]                    # Valeurs min_samples pour DBSCAN
    
    resultats = []  # Liste pour stocker tous les résultats
    debut_temps_total = time.time()
    
    # Boucle principale sur les cas de features
    for cas_nom, features in cases_features.items():
        print(f"\n🎯 TRAITEMENT {cas_nom.upper()} - {len(features)} features")
        
        # Vérification de la disponibilité des features
        features_disponibles = [f for f in features if f in df_spotify.columns]
        if len(features_disponibles) != len(features):
            features_manquantes = set(features) - set(features_disponibles)
            print(f"   ❌ Features manquantes: {features_manquantes}")
            continue
        
        # Extraction et nettoyage des données
        X = df_spotify[features_disponibles].copy()
        X_clean = nettoyer_donnees(X)
        
        if len(X_clean) < 100:
            print(f"   ❌ Pas assez de données après nettoyage: {len(X_clean)} lignes")
            continue
        
        # Test avec chaque scaler
        for scaler_nom, scaler in scalers.items():
            print(f"   🔧 Preprocessing avec {scaler_nom}")
            
            try:
                # Application du scaler
                # fit calcule les paramètres de normalisation (moyenne, écart-type, etc.)
                # transform applique la normalisation aux données
                X_scaled = scaler.fit_transform(X_clean)
                
                # Tests K-means avec différents nombres de clusters
                for k_clusters in kmeans_k_values:
                    if k_clusters > len(X_scaled):  # Éviter k > nombre d'échantillons
                        continue
                    
                    # Test de la configuration K-means
                    resultats_test = tester_configuration_clustering(
                        X_scaled, 'KMeans', k_clusters=k_clusters
                    )
                    
                    if resultats_test is not None:
                        # Ajout des métadonnées à chaque résultat
                        resultats_test.update({
                            'cas': cas_nom,
                            'features_count': len(features_disponibles),
                            'features_list': ', '.join(features_disponibles),
                            'scaler': scaler_nom,
                            'modele_clustering': 'KMeans',
                            'k_clusters': k_clusters,
                            'eps': None,
                            'min_samples': None
                        })
                        resultats.append(resultats_test)
                
                # Tests DBSCAN avec différents paramètres
                for eps in eps_values:
                    for min_samples in min_samples_values:
                        # Test de la configuration DBSCAN
                        resultats_test = tester_configuration_clustering(
                            X_scaled, 'DBSCAN', eps=eps, min_samples=min_samples
                        )
                        
                        if resultats_test is not None:
                            resultats_test.update({
                                'cas': cas_nom,
                                'features_count': len(features_disponibles),
                                'features_list': ', '.join(features_disponibles),
                                'scaler': scaler_nom,
                                'modele_clustering': 'DBSCAN',
                                'k_clusters': None,
                                'eps': eps,
                                'min_samples': min_samples
                            })
                            resultats.append(resultats_test)
                            
            except Exception as e:
                print(f"   ❌ Erreur avec {scaler_nom}: {str(e)}")
                continue
    
    # Statistiques finales
    duree_totale = time.time() - debut_temps_total
    print(f"\n🏁 TESTS TERMINÉS:")
    print(f"   • Configurations testées: {len(resultats):,}")
    print(f"   • Durée totale: {duree_totale:.1f}s ({duree_totale/60:.1f} min)")
    
    return resultats

def analyser_resultats(resultats):
    """
    Analyse les résultats et identifie les meilleures configurations.
    
    Args:
        resultats (list): Liste des résultats de tous les tests
        
    Returns:
        dict: Analyses et recommandations
    """
    if not resultats:
        print("❌ Aucun résultat à analyser")
        return {}
    
    print(f"\n📊 ANALYSE DES RÉSULTATS - {len(resultats):,} configurations")
    
    # Conversion en DataFrame pour faciliter l'analyse
    df_resultats = pd.DataFrame(resultats)
    
    # Calcul d'un score composite normalisé
    # Normalisation de chaque métrique entre 0 et 1
    min_sil = df_resultats['silhouette_score'].min()
    max_sil = df_resultats['silhouette_score'].max()
    df_resultats['sil_norm'] = (df_resultats['silhouette_score'] - min_sil) / (max_sil - min_sil)
    
    # Davies-Bouldin: plus bas = meilleur, donc inversion de l'échelle
    min_db = df_resultats['davies_bouldin_score'].min()
    max_db = df_resultats['davies_bouldin_score'].max()
    df_resultats['db_norm'] = 1 - ((df_resultats['davies_bouldin_score'] - min_db) / (max_db - min_db))
    
    min_ch = df_resultats['calinski_harabasz_score'].min()
    max_ch = df_resultats['calinski_harabasz_score'].max()
    df_resultats['ch_norm'] = (df_resultats['calinski_harabasz_score'] - min_ch) / (max_ch - min_ch)
    
    # Score composite pondéré (40% Silhouette + 30% Davies-Bouldin + 30% Calinski-Harabasz)
    df_resultats['score_composite'] = (
        df_resultats['sil_norm'] * 0.4 + 
        df_resultats['db_norm'] * 0.3 + 
        df_resultats['ch_norm'] * 0.3
    )
    
    # Identification du TOP 5
    top5_global = df_resultats.nlargest(5, 'score_composite')
    
    print(f"\n🏆 TOP 5 MEILLEURES CONFIGURATIONS:")
    print("="*80)
    
    for idx, (_, row) in enumerate(top5_global.iterrows(), 1):
        print(f"\n🥇 RANG #{idx}")
        print(f"   Modèle: {row['modele_clustering']}")
        if row['modele_clustering'] == 'KMeans':
            print(f"   Paramètres: k_clusters={row['k_clusters']}")
        else:
            print(f"   Paramètres: eps={row['eps']}, min_samples={row['min_samples']}")
        print(f"   Cas features: {row['cas']} ({row['features_count']} features)")
        print(f"   Scaler: {row['scaler']}")
        print(f"   Score composite: {row['score_composite']:.4f}")
        print(f"   Silhouette: {row['silhouette_score']:.4f}")
        print(f"   Davies-Bouldin: {row['davies_bouldin_score']:.4f}")
        print(f"   Calinski-Harabasz: {row['calinski_harabasz_score']:.2f}")
    
    # Sauvegarde des résultats
    try:
        df_resultats.to_csv('resultats_clustering_complets.csv', index=False)
        top5_global.to_csv('top5_configurations.csv', index=False)
        print(f"\n💾 Fichiers sauvegardés:")
        print(f"   • resultats_clustering_complets.csv")
        print(f"   • top5_configurations.csv")
    except Exception as e:
        print(f"❌ Erreur lors de la sauvegarde: {e}")
    
    return {
        'tous_resultats': df_resultats,
        'top5_global': top5_global,
        'meilleur_modele': top5_global.iloc[0]
    }

def main():
    """
    Fonction principale qui orchestre l'analyse complète.
    """
    print("🚀 LANCEMENT DE L'ANALYSE ML CLUSTERING MUSICAL")
    print(f"⏰ Début: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # Installation des dépendances optionnelles
        installer_dependances()
        
        # Chargement des données
        df_spotify = charger_donnees_spotify()
        
        # Analyse complète
        resultats = analyser_clustering_complet(df_spotify)
        
        # Analyse des résultats
        analyses = analyser_resultats(resultats)
        
        print(f"\n🎉 ANALYSE TERMINÉE AVEC SUCCÈS!")
        print(f"⏰ Fin: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        return analyses
        
    except Exception as e:
        print(f"❌ ERREUR: {e}")
        import traceback
        traceback.print_exc()
        return None

# Point d'entrée du script
if __name__ == "__main__":
    resultats_finaux = main()

🚀 LANCEMENT DE L'ANALYSE ML CLUSTERING MUSICAL
⏰ Début: 2025-06-24 11:26:03
✓ tqdm disponible pour barres de progression
✓ fpdf2 disponible pour génération PDF
✓ Données chargées avec succès depuis: ../Datasets/df_concat_tagged.csv
✓ Forme du DataFrame: (5403, 18)
🎵 DÉBUT DE L'ANALYSE CLUSTERING MUSICAL
📊 Données chargées: 5,403 lignes, 18 colonnes

🎯 TRAITEMENT CAS1 - 7 features
   🧹 Nettoyage données: 5,403 lignes avant nettoyage
   ✅ Données nettoyées: 5,403 lignes après nettoyage
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🎯 TRAITEMENT CAS2 - 6 features
   🧹 Nettoyage données: 5,403 lignes avant nettoyage
   ✅ Données nettoyées: 5,403 lignes après nettoyage
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🎯 TRAITEMENT CAS3 - 5 features
   🧹 Nettoyage données: 5,403 lignes avant nettoyage
   ✅ Données nettoyées: 5,403 lignes après nettoyage
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🏁 TESTS TERMINÉS:
   • Configurations testées: 166
   • Durée totale: 320.9s (5.3 min)

📊 ANALYSE DES RÉSULTATS - 166 configurations

🏆 TOP 5 MEILLEURES CONFIGURATIONS:
================================================================================

🥇 RANG #1
   Modèle: DBSCAN
   Paramètres: eps=1.5, min_samples=3.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.9014
   Silhouette: 0.8005
   Davies-Bouldin: 0.4314
   Calinski-Harabasz: 3472722.33

🥇 RANG #2
   Modèle: KMeans
   Paramètres: k_clusters=2.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.7051
   Silhouette: 0.9616
   Davies-Bouldin: 0.1673
   Calinski-Harabasz: 59105.10

🥇 RANG #3
   Modèle: KMeans
   Paramètres: k_clusters=3.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6733
   Silhouette: 0.9523
   Davies-Bouldin: 0.3279
   Calinski-Harabasz: 90981.01

🥇 RANG #4
   Modèle: KMeans
   Paramètres: k_clusters=25.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6701
   Silhouette: 0.8683
   Davies-Bouldin: 0.4674
   Calinski-Harabasz: 654560.92

🥇 RANG #5
   Modèle: KMeans
   Paramètres: k_clusters=20.0
   Cas features: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6641
   Silhouette: 0.9012
   Davies-Bouldin: 0.4812
   Calinski-Harabasz: 507085.60

💾 Fichiers sauvegardés:
   • resultats_clustering_complets.csv
   • top5_configurations.csv

🎉 ANALYSE TERMINÉE AVEC SUCCÈS!
⏰ Fin: 2025-06-24 11:31:24

#### Résultats

##### Résultats globaux

In [11]:
df_resultats_globaux = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/resultats_clustering_complets.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_resultats_globaux

,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,duree_calcul_sec,timestamp,cas,features_count,features_list,scaler,modele_clustering,k_clusters,eps,min_samples,n_clusters_detectes,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,0.342094,1.347416,2118.826048,5403,1.666160,2025-06-24 11:26:04,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,2.0,NaN,NaN,NaN,NaN,0.556528,0.217596,6.086347e-04,0.288073
1,0.276683,1.230408,1986.473428,5403,1.453521,2025-06-24 11:26:06,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,3.0,NaN,NaN,NaN,NaN,0.509703,0.295173,5.705225e-04,0.292604
2,0.198888,1.501536,1787.099613,5403,1.241869,2025-06-24 11:26:07,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,4.0,NaN,NaN,NaN,NaN,0.454013,0.115415,5.131111e-04,0.216384
3,0.193390,1.404206,1655.312477,5403,1.590698,2025-06-24 11:26:09,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,5.0,NaN,NaN,NaN,NaN,0.450078,0.179945,4.751618e-04,0.234157
4,0.190992,1.326393,1450.366250,5403,1.345544,2025-06-24 11:26:10,cas1,7,"valence, energy, danceability, acousticness, t...",StandardScaler,KMeans,7.0,NaN,NaN,NaN,NaN,0.448361,0.231535,4.161457e-04,0.248930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,-0.133542,1.193926,78.603442,1054,0.752101,2025-06-24 11:30:55,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.3,10.0,25.0,0.0,0.216041,0.319361,2.113429e-05,0.182231
162,-0.230535,0.846615,8.058357,5232,5.997735,2025-06-24 11:31:01,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,3.0,14.0,0.0,0.146608,0.549629,8.202005e-07,0.223532
163,0.185849,0.612405,16.484363,5136,5.815467,2025-06-24 11:31:06,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,5.0,4.0,0.0,0.444679,0.704910,3.246544e-06,0.389346
164,-0.071282,0.917260,23.791211,5049,6.387831,2025-06-24 11:31:13,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,7.0,5.0,0.0,0.260610,0.502791,5.350617e-06,0.255083
165,0.400192,0.530824,48.623634,4912,5.130233,2025-06-24 11:31:18,cas3,5,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,0.5,10.0,2.0,0.0,0.598117,0.758999,1.250134e-05,0.466950

##### Top 5 configurations

In [12]:
df_Top_5_configurations = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/top5_configurations.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_Top_5_configurations

,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,duree_calcul_sec,timestamp,cas,features_count,features_list,scaler,modele_clustering,k_clusters,eps,min_samples,n_clusters_detectes,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,0.800550,0.431446,3.472722e+06,4623,5.111118,2025-06-24 11:27:54,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,DBSCAN,NaN,1.5,3.0,24.0,0.0,0.884716,0.824887,1.000000,0.901352
1,0.961593,0.167324,5.910510e+04,5403,1.605159,2025-06-24 11:27:24,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,2.0,NaN,NaN,NaN,NaN,1.000000,1.000000,0.017018,0.705106
2,0.952270,0.327891,9.098101e+04,5403,1.404680,2025-06-24 11:27:25,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,3.0,NaN,NaN,NaN,NaN,0.993326,0.893544,0.026197,0.673253
3,0.868258,0.467364,6.545609e+05,5403,1.129442,2025-06-24 11:27:35,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,25.0,NaN,NaN,NaN,NaN,0.933185,0.801073,0.188485,0.670141
4,0.901174,0.481162,5.070856e+05,5403,1.853820,2025-06-24 11:27:34,cas1,7,"valence, energy, danceability, acousticness, t...",RobustScaler,KMeans,20.0,NaN,NaN,NaN,NaN,0.956749,0.791925,0.146018,0.664082

### Version 2

In [13]:
# =============================================================================
# ANALYSE ML CLUSTERING MUSICAL AVEC GÉNÉRATION PDF ET DÉPLOIEMENT STREAMLIT
# =============================================================================

# Imports standards - regroupés selon les bonnes pratiques PEP-8
import os  # Module pour les opérations système d'exploitation
import sys  # Module pour l'accès aux variables de l'interpréteur Python
import time  # Module pour la gestion du temps et des mesures de performance
import warnings  # Module pour la gestion des avertissements Python
import platform  # Module pour obtenir des informations sur la plateforme système
import subprocess  # Module pour l'exécution de commandes système
from datetime import datetime  # Classe pour la manipulation des dates et heures
import pickle  # Module pour la sérialisation d'objets Python

# Imports tiers - bibliothèques externes installées via pip
import pandas as pd  # Bibliothèque pour la manipulation de données tabulaires
import numpy as np  # Bibliothèque pour le calcul numérique et les opérations sur arrays
import matplotlib.pyplot as plt  # Bibliothèque pour la création de graphiques
import seaborn as sns  # Bibliothèque pour la visualisation statistique avancée

# Imports scikit-learn - modules spécifiques pour le machine learning
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

# Configuration des avertissements
warnings.filterwarnings('ignore')  # Supprime les messages d'avertissement

# Variables globales pour les dépendances
TQDM_AVAILABLE = False
PDF_AVAILABLE = False
STREAMLIT_AVAILABLE = False

def installer_dependances():
    """
    Installe et importe toutes les dépendances nécessaires.
    
    Returns:
        tuple: Status des dépendances (tqdm, fpdf, streamlit)
    """
    global TQDM_AVAILABLE, PDF_AVAILABLE, STREAMLIT_AVAILABLE
    
    # Installation de tqdm pour les barres de progression
    try:
        from tqdm import tqdm
        TQDM_AVAILABLE = True
        print("✓ tqdm disponible")
    except ImportError:
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "tqdm"])
            from tqdm import tqdm
            TQDM_AVAILABLE = True
            print("✓ tqdm installé avec succès")
        except Exception as e:
            print(f"❌ Erreur installation tqdm: {e}")
            TQDM_AVAILABLE = False
    
    # Installation de fpdf2 pour la génération PDF
    try:
        from fpdf import FPDF
        PDF_AVAILABLE = True
        print("✓ fpdf2 disponible")
    except ImportError:
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "fpdf2"])
            from fpdf import FPDF
            PDF_AVAILABLE = True
            print("✓ fpdf2 installé avec succès")
        except Exception as e:
            print(f"❌ Erreur installation fpdf2: {e}")
            PDF_AVAILABLE = False
    
    # Installation de streamlit pour le déploiement web
    try:
        import streamlit as st
        STREAMLIT_AVAILABLE = True
        print("✓ streamlit disponible")
    except ImportError:
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit"])
            import streamlit as st
            STREAMLIT_AVAILABLE = True
            print("✓ streamlit installé avec succès")
        except Exception as e:
            print(f"❌ Erreur installation streamlit: {e}")
            STREAMLIT_AVAILABLE = False
    
    return TQDM_AVAILABLE, PDF_AVAILABLE, STREAMLIT_AVAILABLE

def charger_donnees_spotify():
    """
    Charge les données Spotify depuis le fichier CSV avec gestion multi-OS.
    
    Returns:
        pd.DataFrame: DataFrame contenant les données Spotify
    """
    system = platform.system()  # Détection du système d'exploitation
    
    # Liste des chemins possibles selon l'OS et la structure du projet
    chemins_possibles = [
        "./Datasets/df_concat_tagged.csv",
        "./df_concat_tagged.csv",
        "df_concat_tagged.csv",
        "../Datasets/df_concat_tagged.csv",
        "/Users/bertranddevulder/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_et_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/df_concat_tagged.csv",
        r"C:\Users\beber\Documents\Cours\Wild_Code_School\Semaine_8_Visualisation_interactive_&_Pandas_approfondi\Projet_2\Projet_2_local\Datasets\df_concat_tagged.csv"
    ]
    
    # Tentative de chargement avec chaque chemin
    for chemin in chemins_possibles:
        try:
            df_spotify = pd.read_csv(chemin)  # Lecture du fichier CSV
            print(f"✓ Données chargées: {chemin}")
            print(f"✓ Shape: {df_spotify.shape}")
            return df_spotify
        except FileNotFoundError:
            continue
        except Exception as e:
            print(f"Erreur {chemin}: {e}")
            continue
    
    raise FileNotFoundError("❌ Fichier df_concat_tagged.csv introuvable")

def definir_cas_features():
    """
    Définit les trois cas de features selon les spécifications du projet.
    
    Returns:
        dict: Dictionnaire avec les trois cas de features
    """
    # Cas 1: Ensemble complet avec 7 features
    features_cas1 = [
        'valence',          # Valence émotionnelle (0=triste, 1=joyeux)
        'energy',           # Énergie perçue (0=calme, 1=énergique)
        'danceability',     # Capacité à danser (0=difficile, 1=facile)
        'acousticness',     # Caractère acoustique (0=électronique, 1=acoustique)
        'tempo',            # Tempo en BPM
        'loudness',         # Volume sonore en décibels
        'instrumentalness'  # Caractère instrumental (0=vocal, 1=instrumental)
    ]
    
    # Cas 2: Ensemble réduit sans instrumentalness (6 features)
    features_cas2 = [
        'valence', 'energy', 'danceability', 'acousticness', 'tempo', 'loudness'
    ]
    
    # Cas 3: Ensemble minimal (5 features principales)
    features_cas3 = [
        'valence', 'energy', 'danceability', 'acousticness', 'tempo'
    ]
    
    return {
        'cas1': features_cas1,
        'cas2': features_cas2,
        'cas3': features_cas3
    }

def nettoyer_donnees(X):
    """
    Nettoie les données en supprimant les valeurs manquantes et infinies.
    
    Args:
        X (pd.DataFrame): DataFrame avec les features à nettoyer
        
    Returns:
        pd.DataFrame: DataFrame nettoyé
    """
    print(f"   🧹 Nettoyage: {len(X):,} lignes avant")
    
    # Suppression des valeurs manquantes (NaN)
    X_clean = X.dropna()
    
    # Remplacement des valeurs infinies par NaN puis suppression
    X_clean = X_clean.replace([np.inf, -np.inf], np.nan).dropna()
    
    print(f"   ✅ Nettoyage: {len(X_clean):,} lignes après")
    
    return X_clean

def tester_configuration_clustering(X_scaled, modele_type, **params):
    """
    Teste une configuration de clustering et calcule les métriques.
    
    Args:
        X_scaled (np.array): Données préprocessées
        modele_type (str): 'KMeans' ou 'DBSCAN'
        **params: Paramètres spécifiques au modèle
        
    Returns:
        dict: Résultats avec métriques ou None si échec
    """
    try:
        debut_test = time.time()  # Chronométrage du test
        
        if modele_type == 'KMeans':
            # Création du modèle K-means avec paramètres optimisés
            modele = KMeans(
                n_clusters=params['k_clusters'],  # Nombre de clusters
                random_state=42,                  # Reproductibilité
                n_init=10                         # Nombre d'initialisations
            )
            labels = modele.fit_predict(X_scaled)  # Entraînement et prédiction
            
        elif modele_type == 'DBSCAN':
            # Création du modèle DBSCAN pour clustering basé densité
            modele = DBSCAN(
                eps=params['eps'],                # Distance maximale entre points
                min_samples=params['min_samples'] # Points min pour cluster dense
            )
            labels = modele.fit_predict(X_scaled)
            
            # Vérification du nombre de clusters détectés
            n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
            if n_clusters < 2:  # Minimum 2 clusters requis
                return None
            
            # Filtrage du bruit (points étiquetés -1)
            mask_no_noise = labels != -1
            if np.sum(mask_no_noise) < 10:  # Vérif points restants
                return None
                
            X_scaled = X_scaled[mask_no_noise]  # Application du filtre
            labels = labels[mask_no_noise]
        
        # Vérification finale du nombre de clusters
        n_clusters_unique = len(np.unique(labels))
        if n_clusters_unique < 2:
            return None
        
        # Calcul des métriques d'évaluation du clustering
        # Silhouette Score: cohésion interne vs séparation externe (-1 à 1)
        sil_score = silhouette_score(X_scaled, labels)
        
        # Davies-Bouldin Score: compacité/séparation (0 à ∞, plus bas = meilleur)
        db_score = davies_bouldin_score(X_scaled, labels)
        
        # Calinski-Harabasz Score: variance inter/intra clusters (plus haut = meilleur)
        ch_score = calinski_harabasz_score(X_scaled, labels)
        
        duree_test = time.time() - debut_test  # Temps d'exécution
        
        # Construction du dictionnaire de résultats
        resultats = {
            'silhouette_score': sil_score,
            'davies_bouldin_score': db_score,
            'calinski_harabasz_score': ch_score,
            'n_samples': len(X_scaled),
            'duree_calcul_sec': duree_test,
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'modele_objet': modele  # Sauvegarde du modèle entraîné
        }
        
        # Ajout de métriques spécifiques DBSCAN
        if modele_type == 'DBSCAN':
            resultats.update({
                'n_clusters_detectes': n_clusters,
                'noise_points': np.sum(labels == -1) if modele_type == 'DBSCAN' else 0
            })
        
        return resultats
        
    except Exception as e:
        return None  # Gestion silencieuse des erreurs

def analyser_clustering_complet(df_spotify):
    """
    Effectue l'analyse complète de clustering avec tous les paramètres.
    
    Args:
        df_spotify (pd.DataFrame): DataFrame Spotify complet
        
    Returns:
        list: Liste des résultats de tous les tests
    """
    print("🎵 DÉBUT ANALYSE CLUSTERING MUSICAL")
    print(f"📊 Données: {df_spotify.shape[0]:,} lignes, {df_spotify.shape[1]} colonnes")
    
    # Définition des paramètres d'expérimentation
    cases_features = definir_cas_features()
    
    # Scalers pour la normalisation des données
    scalers = {
        'StandardScaler': StandardScaler(),    # Z-score normalization
        'MinMaxScaler': MinMaxScaler(),        # Min-max normalization
        'RobustScaler': RobustScaler()         # Robust normalization (médiane/IQR)
    }
    
    # Grilles de paramètres pour les algorithmes
    kmeans_k_values = [2, 3, 4, 5, 7, 10, 15, 20, 25]
    eps_values = [0.3, 0.5, 0.7, 1.0, 1.5]
    min_samples_values = [3, 5, 7, 10]
    
    resultats = []  # Liste pour stocker tous les résultats
    debut_temps_total = time.time()
    
    # Boucle principale sur les cas de features
    for cas_nom, features in cases_features.items():
        print(f"\n🎯 TRAITEMENT {cas_nom.upper()} - {len(features)} features")
        
        # Vérification de la disponibilité des features dans les données
        features_disponibles = [f for f in features if f in df_spotify.columns]
        if len(features_disponibles) != len(features):
            features_manquantes = set(features) - set(features_disponibles)
            print(f"   ❌ Features manquantes: {features_manquantes}")
            continue
        
        # Extraction et nettoyage des données pour ce cas
        X = df_spotify[features_disponibles].copy()
        X_clean = nettoyer_donnees(X)
        
        if len(X_clean) < 100:
            print(f"   ❌ Données insuffisantes: {len(X_clean)} lignes")
            continue
        
        # Test avec chaque méthode de normalisation
        for scaler_nom, scaler in scalers.items():
            print(f"   🔧 Preprocessing avec {scaler_nom}")
            
            try:
                # Application de la normalisation
                X_scaled = scaler.fit_transform(X_clean)
                
                # Tests K-means avec différents nombres de clusters
                for k_clusters in kmeans_k_values:
                    if k_clusters > len(X_scaled):  # Éviter k > n_samples
                        continue
                    
                    # Test de la configuration K-means
                    resultats_test = tester_configuration_clustering(
                        X_scaled, 'KMeans', k_clusters=k_clusters
                    )
                    
                    if resultats_test is not None:
                        # Ajout des métadonnées de configuration
                        resultats_test.update({
                            'cas': cas_nom,
                            'features_count': len(features_disponibles),
                            'features_list': ', '.join(features_disponibles),
                            'scaler': scaler_nom,
                            'scaler_objet': scaler,  # Sauvegarde du scaler
                            'modele_clustering': 'KMeans',
                            'k_clusters': k_clusters,
                            'eps': None,
                            'min_samples': None,
                            'X_clean': X_clean  # Sauvegarde des données nettoyées
                        })
                        resultats.append(resultats_test)
                
                # Tests DBSCAN avec différents paramètres
                for eps in eps_values:
                    for min_samples in min_samples_values:
                        # Test de la configuration DBSCAN
                        resultats_test = tester_configuration_clustering(
                            X_scaled, 'DBSCAN', eps=eps, min_samples=min_samples
                        )
                        
                        if resultats_test is not None:
                            # Ajout des métadonnées de configuration
                            resultats_test.update({
                                'cas': cas_nom,
                                'features_count': len(features_disponibles),
                                'features_list': ', '.join(features_disponibles),
                                'scaler': scaler_nom,
                                'scaler_objet': scaler,
                                'modele_clustering': 'DBSCAN',
                                'k_clusters': None,
                                'eps': eps,
                                'min_samples': min_samples,
                                'X_clean': X_clean
                            })
                            resultats.append(resultats_test)
                            
            except Exception as e:
                print(f"   ❌ Erreur {scaler_nom}: {str(e)}")
                continue
    
    # Statistiques finales
    duree_totale = time.time() - debut_temps_total
    print(f"\n🏁 TESTS TERMINÉS:")
    print(f"   • Configurations testées: {len(resultats):,}")
    print(f"   • Durée totale: {duree_totale:.1f}s")
    
    return resultats

def analyser_resultats(resultats):
    """
    Analyse les résultats et identifie les meilleures configurations.
    
    Args:
        resultats (list): Liste des résultats de tous les tests
        
    Returns:
        dict: Analyses et recommandations
    """
    if not resultats:
        print("❌ Aucun résultat à analyser")
        return {}
    
    print(f"\n📊 ANALYSE RÉSULTATS - {len(resultats):,} configurations")
    
    # Conversion en DataFrame pour faciliter l'analyse
    df_resultats = pd.DataFrame(resultats)
    
    # Calcul d'un score composite normalisé
    # Normalisation de chaque métrique entre 0 et 1
    min_sil = df_resultats['silhouette_score'].min()
    max_sil = df_resultats['silhouette_score'].max()
    df_resultats['sil_norm'] = (df_resultats['silhouette_score'] - min_sil) / (max_sil - min_sil)
    
    # Davies-Bouldin: inversion car plus bas = meilleur
    min_db = df_resultats['davies_bouldin_score'].min()
    max_db = df_resultats['davies_bouldin_score'].max()
    df_resultats['db_norm'] = 1 - ((df_resultats['davies_bouldin_score'] - min_db) / (max_db - min_db))
    
    # Calinski-Harabasz: normalisation directe
    min_ch = df_resultats['calinski_harabasz_score'].min()
    max_ch = df_resultats['calinski_harabasz_score'].max()
    df_resultats['ch_norm'] = (df_resultats['calinski_harabasz_score'] - min_ch) / (max_ch - min_ch)
    
    # Score composite pondéré (40% Silhouette + 30% Davies-Bouldin + 30% Calinski-Harabasz)
    df_resultats['score_composite'] = (
        df_resultats['sil_norm'] * 0.4 + 
        df_resultats['db_norm'] * 0.3 + 
        df_resultats['ch_norm'] * 0.3
    )
    
    # Identification du TOP 5 des meilleures configurations
    top5_global = df_resultats.nlargest(5, 'score_composite')
    
    print(f"\n🏆 TOP 5 MEILLEURES CONFIGURATIONS:")
    print("="*80)
    
    # Affichage détaillé du TOP 5
    for idx, (_, row) in enumerate(top5_global.iterrows(), 1):
        print(f"\n🥇 RANG #{idx}")
        print(f"   Modèle: {row['modele_clustering']}")
        if row['modele_clustering'] == 'KMeans':
            print(f"   Paramètres: k_clusters={row['k_clusters']}")
        else:
            print(f"   Paramètres: eps={row['eps']}, min_samples={row['min_samples']}")
        print(f"   Cas: {row['cas']} ({row['features_count']} features)")
        print(f"   Scaler: {row['scaler']}")
        print(f"   Score composite: {row['score_composite']:.4f}")
        print(f"   Silhouette: {row['silhouette_score']:.4f}")
        print(f"   Davies-Bouldin: {row['davies_bouldin_score']:.4f}")
        print(f"   Calinski-Harabasz: {row['calinski_harabasz_score']:.2f}")
    
    # Sauvegarde des résultats en CSV
    try:
        df_resultats.to_csv('resultats_clustering_complets.csv', index=False)
        top5_global.to_csv('top5_configurations.csv', index=False)
        print(f"\n💾 Fichiers CSV sauvegardés")
    except Exception as e:
        print(f"❌ Erreur sauvegarde CSV: {e}")
    
    return {
        'tous_resultats': df_resultats,
        'top5_global': top5_global,
        'meilleur_modele': top5_global.iloc[0]
    }

def sauvegarder_meilleur_modele(meilleur_config):
    """
    Sauvegarde le meilleur modèle et ses composants pour le déploiement.
    
    Args:
        meilleur_config (pd.Series): Configuration du meilleur modèle
        
    Returns:
        dict: Chemins des fichiers sauvegardés
    """
    try:
        # Création du dossier de sauvegarde
        os.makedirs('modeles_deploiement', exist_ok=True)
        
        # Sauvegarde du modèle entraîné
        with open('modeles_deploiement/meilleur_modele.pkl', 'wb') as f:
            pickle.dump(meilleur_config['modele_objet'], f)
        
        # Sauvegarde du scaler
        with open('modeles_deploiement/scaler.pkl', 'wb') as f:
            pickle.dump(meilleur_config['scaler_objet'], f)
        
        # Sauvegarde des métadonnées de configuration
        config_metadata = {
            'modele_type': meilleur_config['modele_clustering'],
            'cas': meilleur_config['cas'],
            'features_list': meilleur_config['features_list'].split(', '),
            'scaler_type': meilleur_config['scaler'],
            'parametres': {
                'k_clusters': meilleur_config.get('k_clusters'),
                'eps': meilleur_config.get('eps'),
                'min_samples': meilleur_config.get('min_samples')
            },
            'scores': {
                'silhouette': meilleur_config['silhouette_score'],
                'davies_bouldin': meilleur_config['davies_bouldin_score'],
                'calinski_harabasz': meilleur_config['calinski_harabasz_score'],
                'score_composite': meilleur_config['score_composite']
            }
        }
        
        # Sauvegarde des métadonnées en pickle
        with open('modeles_deploiement/config_metadata.pkl', 'wb') as f:
            pickle.dump(config_metadata, f)
        
        print("✅ Modèle sauvegardé dans modeles_deploiement/")
        
        return {
            'modele_path': 'modeles_deploiement/meilleur_modele.pkl',
            'scaler_path': 'modeles_deploiement/scaler.pkl',
            'config_path': 'modeles_deploiement/config_metadata.pkl'
        }
        
    except Exception as e:
        print(f"❌ Erreur sauvegarde modèle: {e}")
        return {}

class RapportPDF:
    """
    Classe pour générer un rapport PDF des résultats de clustering.
    """
    
    def __init__(self):
        """
        Initialise la classe PDF avec les paramètres de base.
        """
        if not PDF_AVAILABLE:
            raise ImportError("fpdf2 non disponible. Installez-le avec: pip install fpdf2")
        
        from fpdf import FPDF  # Import local pour éviter les erreurs
        
        # Création de l'objet PDF avec format A4 portrait
        self.pdf = FPDF(orientation='P', unit='mm', format='A4')
        
        # Configuration des marges (gauche, haut, droite)
        self.pdf.set_margins(20, 20, 20)
        
        # Activation du saut de page automatique à 20mm du bas
        self.pdf.set_auto_page_break(auto=True, margin=20)
    
    def ajouter_page_titre(self):
        """
        Ajoute la page de titre du rapport.
        """
        self.pdf.add_page()  # Ajout d'une nouvelle page
        
        # Configuration de la police pour le titre principal
        self.pdf.set_font('Arial', 'B', 24)  # Arial Bold 24pt
        self.pdf.set_text_color(0, 51, 102)  # Couleur bleu foncé (RGB)
        
        # Positionnement vertical pour centrer le titre
        self.pdf.ln(40)  # Saut de ligne de 40mm
        
        # Titre principal centré
        self.pdf.cell(0, 15, 'RAPPORT D\'ANALYSE', ln=True, align='C')
        self.pdf.cell(0, 15, 'CLUSTERING MUSICAL', ln=True, align='C')
        
        # Sous-titre
        self.pdf.set_font('Arial', '', 16)  # Arial normal 16pt
        self.pdf.set_text_color(64, 64, 64)  # Gris foncé
        self.pdf.ln(10)
        self.pdf.cell(0, 10, 'Analyse des caractéristiques audio Spotify', ln=True, align='C')
        
        # Date et heure de génération
        self.pdf.set_font('Arial', '', 12)
        self.pdf.ln(20)
        date_generation = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.pdf.cell(0, 10, f'Généré le : {date_generation}', ln=True, align='C')
        
        # Logo ou décoration (optionnel)
        self.pdf.ln(30)
        self.pdf.set_font('Arial', 'I', 10)
        self.pdf.cell(0, 10, 'Projet Moodify - Wild Code School', ln=True, align='C')
    
    def ajouter_resume_executif(self, analyses):
        """
        Ajoute le résumé exécutif avec les principales conclusions.
        
        Args:
            analyses (dict): Dictionnaire contenant les analyses
        """
        self.pdf.add_page()
        
        # Titre de section
        self.pdf.set_font('Arial', 'B', 18)
        self.pdf.set_text_color(0, 51, 102)
        self.pdf.cell(0, 12, 'RÉSUMÉ EXÉCUTIF', ln=True)
        self.pdf.ln(5)
        
        # Contenu du résumé
        self.pdf.set_font('Arial', '', 11)
        self.pdf.set_text_color(0, 0, 0)
        
        # Nombre total de configurations testées
        nb_configs = len(analyses['tous_resultats'])
        resume_text = f"""
Cette analyse a évalué {nb_configs:,} configurations de clustering différentes 
sur les données musicales Spotify. L'objectif était d'identifier la meilleure 
méthode pour segmenter automatiquement les morceaux selon leurs caractéristiques 
audio afin d'améliorer les recommandations musicales.

MÉTHODOLOGIE :
• 3 cas de features testés (5, 6 et 7 caractéristiques audio)
• 2 algorithmes : K-means et DBSCAN
• 3 méthodes de normalisation : StandardScaler, MinMaxScaler, RobustScaler
• Évaluation par scores Silhouette, Davies-Bouldin et Calinski-Harabasz

RÉSULTATS PRINCIPAUX :
Le meilleur modèle identifié présente un score composite de {analyses['meilleur_modele']['score_composite']:.4f}.
Il s'agit d'un algorithme {analyses['meilleur_modele']['modele_clustering']} utilisant 
{analyses['meilleur_modele']['features_count']} features avec normalisation {analyses['meilleur_modele']['scaler']}.

RECOMMANDATIONS :
Ce modèle est recommandé pour le déploiement en production dans l'application 
Streamlit pour les recommandations musicales personnalisées.
        """
        
        # Utilisation de multi_cell pour le texte multiligne
        self.pdf.multi_cell(0, 6, resume_text.strip(), align='J')
    
    def ajouter_top5_configurations(self, top5):
        """
        Ajoute le tableau du TOP 5 des meilleures configurations.
        
        Args:
            top5 (pd.DataFrame): DataFrame du TOP 5
        """
        self.pdf.add_page()
        
        # Titre de section
        self.pdf.set_font('Arial', 'B', 18)
        self.pdf.set_text_color(0, 51, 102)
        self.pdf.cell(0, 12, 'TOP 5 MEILLEURES CONFIGURATIONS', ln=True)
        self.pdf.ln(5)
        
        # En-têtes du tableau
        self.pdf.set_font('Arial', 'B', 9)
        self.pdf.set_fill_color(230, 230, 230)  # Gris clair pour l'en-tête
        
        # Largeurs des colonnes
        col_widths = [15, 25, 20, 25, 20, 25, 25, 25]
        headers = ['Rang', 'Modèle', 'Cas', 'Scaler', 'Params', 'Silhouette', 'Davies-B.', 'Score Comp.']
        
        # Création de l'en-tête du tableau
        for i, header in enumerate(headers):
            self.pdf.cell(col_widths[i], 8, header, border=1, align='C', fill=True)
        self.pdf.ln()
        
        # Contenu du tableau
        self.pdf.set_font('Arial', '', 8)
        self.pdf.set_fill_color(255, 255, 255)  # Blanc pour le contenu
        
        # Boucle sur les 5 meilleures configurations
        for idx, (_, row) in enumerate(top5.iterrows(), 1):
            # Formatage des paramètres selon le type de modèle
            if row['modele_clustering'] == 'KMeans':
                params = f"k={row['k_clusters']}"
            else:
                params = f"eps={row['eps']:.1f}"
            
            # Données de la ligne
            data = [
                str(idx),
                row['modele_clustering'],
                row['cas'],
                row['scaler'],
                params,
                f"{row['silhouette_score']:.3f}",
                f"{row['davies_bouldin_score']:.3f}",
                f"{row['score_composite']:.4f}"
            ]
            
            # Création de la ligne
            for i, cell_data in enumerate(data):
                self.pdf.cell(col_widths[i], 6, cell_data, border=1, align='C')
            self.pdf.ln()
    
    def ajouter_recommandations_deploiement(self, meilleur_modele):
        """
        Ajoute les recommandations pour le déploiement.
        
        Args:
            meilleur_modele (pd.Series): Configuration du meilleur modèle
        """
        self.pdf.add_page()
        
        # Titre de section
        self.pdf.set_font('Arial', 'B', 18)
        self.pdf.set_text_color(0, 51, 102)
        self.pdf.cell(0, 12, 'RECOMMANDATIONS POUR LE DÉPLOIEMENT', ln=True)
        self.pdf.ln(5)
        
        # Sous-titre configuration recommandée
        self.pdf.set_font('Arial', 'B', 14)
        self.pdf.set_text_color(0, 102, 51)  # Vert
        self.pdf.cell(0, 10, 'CONFIGURATION RECOMMANDÉE', ln=True)
        self.pdf.ln(3)
        
        # Détails de la configuration recommandée
        self.pdf.set_font('Arial', '', 11)
        self.pdf.set_text_color(0, 0, 0)
        
        config_details = f"""
• Algorithme : {meilleur_modele['modele_clustering']}
• Features utilisées : {meilleur_modele['features_list']}
• Normalisation : {meilleur_modele['scaler']}
• Performances :
  - Score Silhouette : {meilleur_modele['silhouette_score']:.4f}
  - Score Davies-Bouldin : {meilleur_modele['davies_bouldin_score']:.4f}
  - Score Calinski-Harabasz : {meilleur_modele['calinski_harabasz_score']:.2f}
  - Score Composite : {meilleur_modele['score_composite']:.4f}
        """
        
        self.pdf.multi_cell(0, 6, config_details.strip())
        self.pdf.ln(5)
        
        # Recommandations techniques
        self.pdf.set_font('Arial', 'B', 14)
        self.pdf.set_text_color(0, 102, 51)
        self.pdf.cell(0, 10, 'RECOMMANDATIONS TECHNIQUES', ln=True)
        self.pdf.ln(3)
        
        self.pdf.set_font('Arial', '', 11)
        self.pdf.set_text_color(0, 0, 0)
        
        recommandations = """
1. DÉPLOIEMENT STREAMLIT :
   • Utiliser le script app_streamlit.py fourni
   • Charger les modèles pré-entraînés depuis modeles_deploiement/
   • Implémenter la prédiction en temps réel pour les nouvelles chansons

2. ARCHITECTURE RECOMMANDÉE :
   • Séparation des composants : preprocessing, clustering, recommandation
   • Cache des modèles en mémoire pour optimiser les performances
   • Interface utilisateur intuitive avec visualisations interactives

3. MONITORING ET MAINTENANCE :
   • Logging des prédictions pour analyse continue
   • Ré-entraînement périodique avec nouvelles données
   • Tests A/B pour valider l'amélioration des recommandations

4. OPTIMISATIONS FUTURES :
   • Clustering hiérarchique pour sous-genres
   • Intégration de features temporelles (tendances)
   • Personnalisation basée sur l'historique utilisateur
        """
        
        self.pdf.multi_cell(0, 6, recommandations.strip())
    
    def generer_rapport(self, analyses, nom_fichier='rapport_clustering_musical.pdf'):
        """
        Génère le rapport PDF complet.
        
        Args:
            analyses (dict): Dictionnaire des analyses
            nom_fichier (str): Nom du fichier PDF de sortie
            
        Returns:
            str: Chemin du fichier généré
        """
        try:
            print("📄 Génération du rapport PDF...")
            
            # Ajout des différentes sections
            self.ajouter_page_titre()
            self.ajouter_resume_executif(analyses)
            self.ajouter_top5_configurations(analyses['top5_global'])
            self.ajouter_recommandations_deploiement(analyses['meilleur_modele'])
            
            # Sauvegarde du fichier PDF
            self.pdf.output(nom_fichier)
            
            print(f"✅ Rapport PDF généré : {nom_fichier}")
            return nom_fichier
            
        except Exception as e:
            print(f"❌ Erreur génération PDF : {e}")
            return None

def creer_script_streamlit():
    """
    Crée le script Streamlit pour le déploiement de l'application.
    
    Returns:
        str: Nom du fichier créé
    """
    script_content = '''
# =============================================================================
# APPLICATION STREAMLIT - CLUSTERING MUSICAL SPOTIFY
# Script de déploiement pour les recommandations musicales
# =============================================================================

import streamlit as st  # Framework pour applications web interactives
import pandas as pd     # Manipulation de données tabulaires
import numpy as np      # Calculs numériques
import pickle          # Sérialisation/désérialisation d'objets Python
import plotly.express as px  # Visualisations interactives
import plotly.graph_objects as go  # Graphiques Plotly avancés
from sklearn.preprocessing import StandardScaler  # Normalisation des données

# Configuration de la page Streamlit
st.set_page_config(
    page_title="Moodify - Clustering Musical",  # Titre de l'onglet navigateur
    page_icon="🎵",                              # Icône de l'onglet
    layout="wide",                               # Layout large pour plus d'espace
    initial_sidebar_state="expanded"             # Sidebar ouverte par défaut
)

# Cache des modèles pour optimiser les performances
@st.cache_resource  # Décorateur pour mettre en cache les ressources
def charger_modeles():
    """
    Charge les modèles pré-entraînés depuis les fichiers pickle.
    
    Returns:
        tuple: (modele_clustering, scaler, config_metadata)
    """
    try:
        # Chargement du modèle de clustering entraîné
        with open('modeles_deploiement/meilleur_modele.pkl', 'rb') as f:
            modele = pickle.load(f)
        
        # Chargement du scaler pour la normalisation
        with open('modeles_deploiement/scaler.pkl', 'rb') as f:
            scaler = pickle.load(f)
        
        # Chargement des métadonnées de configuration
        with open('modeles_deploiement/config_metadata.pkl', 'rb') as f:
            config = pickle.load(f)
        
        return modele, scaler, config
    
    except FileNotFoundError as e:
        st.error(f"❌ Fichiers modèle non trouvés: {e}")
        st.stop()  # Arrête l'exécution de l'application
    except Exception as e:
        st.error(f"❌ Erreur chargement modèles: {e}")
        st.stop()

@st.cache_data  # Cache pour les données
def charger_donnees_spotify():
    """
    Charge les données Spotify pour l'application.
    
    Returns:
        pd.DataFrame: DataFrame des données musicales
    """
    try:
        # Tentative de chargement du fichier de données
        df = pd.read_csv('Datasets/df_concat_tagged.csv')
        return df
    except FileNotFoundError:
        st.error("❌ Fichier de données non trouvé")
        return None

def predire_cluster(features_dict, modele, scaler, features_list):
    """
    Prédit le cluster pour une nouvelle chanson.
    
    Args:
        features_dict (dict): Dictionnaire des caractéristiques audio
        modele: Modèle de clustering entraîné
        scaler: Scaler pour la normalisation
        features_list (list): Liste des features utilisées
        
    Returns:
        int: Numéro du cluster prédit
    """
    # Création d'un DataFrame avec les features dans le bon ordre
    df_features = pd.DataFrame([features_dict])[features_list]
    
    # Normalisation des features avec le scaler entraîné
    features_scaled = scaler.transform(df_features)
    
    # Prédiction du cluster
    cluster = modele.predict(features_scaled)[0]
    
    return cluster

def afficher_caracteristiques_cluster(df_spotify, cluster_id, features_list):
    """
    Affiche les caractéristiques moyennes d'un cluster.
    
    Args:
        df_spotify (pd.DataFrame): Données Spotify complètes
        cluster_id (int): ID du cluster à analyser
        features_list (list): Liste des features
    """
    # Filtrage des données du cluster
    cluster_data = df_spotify[df_spotify['cluster'] == cluster_id]
    
    if len(cluster_data) > 0:
        # Calcul des statistiques du cluster
        stats = cluster_data[features_list].describe()
        
        # Affichage des caractéristiques moyennes
        st.subheader(f"📊 Caractéristiques du Cluster {cluster_id}")
        
        # Création de colonnes pour l'affichage
        cols = st.columns(len(features_list))
        
        for i, feature in enumerate(features_list):
            with cols[i]:
                # Valeur moyenne de la feature pour ce cluster
                moyenne = stats.loc['mean', feature]
                st.metric(
                    label=feature.capitalize(),
                    value=f"{moyenne:.3f}"
                )

def main():
    """
    Fonction principale de l'application Streamlit.
    """
    # Titre principal de l'application
    st.title("🎵 Moodify - Clustering Musical Spotify")
    st.markdown("*Découvrez à quel style musical appartient votre chanson*")
    
    # Chargement des modèles et données
    modele, scaler, config = charger_modeles()
    df_spotify = charger_donnees_spotify()
    
    if df_spotify is None:
        return
    
    # Affichage des informations sur le modèle utilisé
    with st.sidebar:
        st.header("ℹ️ Informations du Modèle")
        st.write(f"**Algorithme :** {config['modele_type']}")
        st.write(f"**Features :** {len(config['features_list'])}")
        st.write(f"**Normalisation :** {config['scaler_type']}")
        st.write(f"**Score Composite :** {config['scores']['score_composite']:.4f}")
        
        # Métriques de performance
        st.subheader("📈 Performances")
        st.metric("Silhouette Score", f"{config['scores']['silhouette']:.4f}")
        st.metric("Davies-Bouldin", f"{config['scores']['davies_bouldin']:.4f}")
        st.metric("Calinski-Harabasz", f"{config['scores']['calinski_harabasz']:.0f}")
    
    # Interface principale
    st.header("🎼 Analysez votre chanson")
    
    # Création de colonnes pour l'interface utilisateur
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.subheader("🎛️ Caractéristiques Audio")
        
        # Création de sliders pour chaque feature
        features_input = {}
        
        # Définition des ranges pour chaque feature
        feature_ranges = {
            'valence': (0.0, 1.0, 0.5),      # (min, max, default)
            'energy': (0.0, 1.0, 0.5),
            'danceability': (0.0, 1.0, 0.5),
            'acousticness': (0.0, 1.0, 0.5),
            'tempo': (50, 200, 120),
            'loudness': (-30, 0, -10),
            'instrumentalness': (0.0, 1.0, 0.1)
        }
        
        # Création des contrôles pour chaque feature utilisée
        for feature in config['features_list']:
            if feature in feature_ranges:
                min_val, max_val, default_val = feature_ranges[feature]
                
                # Slider pour la feature
                features_input[feature] = st.slider(
                    label=f"{feature.capitalize()}",
                    min_value=min_val,
                    max_value=max_val,
                    value=default_val,
                    step=0.01 if feature != 'tempo' else 1,
                    help=f"Valeur {feature} de la chanson"
                )
    
    with col2:
        st.subheader("🔮 Prédiction")
        
        # Bouton de prédiction
        if st.button("🎯 Prédire le Cluster", type="primary"):
            # Prédiction du cluster
            cluster_predit = predire_cluster(
                features_input, modele, scaler, config['features_list']
            )
            
            # Affichage du résultat
            st.success(f"🎵 Cette chanson appartient au **Cluster {cluster_predit}**")
            
            # Affichage des caractéristiques du cluster
            if 'cluster' in df_spotify.columns:
                afficher_caracteristiques_cluster(
                    df_spotify, cluster_predit, config['features_list']
                )
            
            # Suggestions de chansons similaires
            if 'cluster' in df_spotify.columns:
                chansons_similaires = df_spotify[
                    df_spotify['cluster'] == cluster_predit
                ].head(5)
                
                if len(chansons_similaires) > 0:
                    st.subheader("🎵 Chansons Similaires")
                    for _, chanson in chansons_similaires.iterrows():
                        # Colonnes disponibles peuvent varier
                        if 'track_name' in chanson and 'artist_name' in chanson:
                            st.write(f"• **{chanson['track_name']}** - {chanson['artist_name']}")
    
    # Section visualisations
    st.header("📊 Visualisations")
    
    # Graphique radar des features
    if len(features_input) > 0:
        st.subheader("🕸️ Profil Audio")
        
        # Préparation des données pour le graphique radar
        categories = list(features_input.keys())
        values = list(features_input.values())
        
        # Normalisation des valeurs pour le radar (0-1)
        values_norm = []
        for i, (cat, val) in enumerate(zip(categories, values)):
            if cat in feature_ranges:
                min_val, max_val, _ = feature_ranges[cat]
                val_norm = (val - min_val) / (max_val - min_val)
                values_norm.append(val_norm)
        
        # Création du graphique radar avec Plotly
        fig = go.Figure()
        
        fig.add_trace(go.Scatterpolar(
            r=values_norm,
            theta=categories,
            fill='toself',
            name='Profil Audio'
        ))
        
        fig.update_layout(
            polar=dict(
                radialaxis=dict(
                    visible=True,
                    range=[0, 1]
                )),
            showlegend=True,
            title="Profil Audio de la Chanson"
        )
        
        st.plotly_chart(fig, use_container_width=True)
    
    # Section statistiques globales
    with st.expander("📈 Statistiques Globales"):
        if df_spotify is not None:
            st.write(f"**Nombre total de chansons :** {len(df_spotify):,}")
            
            # Distribution des features
            if len(config['features_list']) > 0:
                feature_stats = df_spotify[config['features_list']].describe()
                st.dataframe(feature_stats)

# Point d'entrée de l'application
if __name__ == "__main__":
    main()
'''
    
    # Sauvegarde du script Streamlit
    nom_fichier = 'app_streamlit.py'
    try:
        with open(nom_fichier, 'w', encoding='utf-8') as f:
            f.write(script_content.strip())
        
        print(f"✅ Script Streamlit créé : {nom_fichier}")
        
        # Instructions de déploiement
        print("\n📋 INSTRUCTIONS DE DÉPLOIEMENT :")
        print("1. Installez les dépendances : pip install streamlit plotly")
        print("2. Lancez l'application : streamlit run app_streamlit.py")
        print("3. L'application sera accessible sur http://localhost:8501")
        
        return nom_fichier
        
    except Exception as e:
        print(f"❌ Erreur création script Streamlit : {e}")
        return None

def creer_fichier_requirements():
    """
    Crée le fichier requirements.txt pour le déploiement.
    
    Returns:
        str: Nom du fichier créé
    """
    requirements = """
# =============================================================================
# REQUIREMENTS.TXT - DÉPENDANCES POUR MOODIFY
# =============================================================================
# Installation : pip install -r requirements.txt

# Core libraries
pandas>=1.5.0
numpy>=1.21.0
scikit-learn>=1.0.0

# Visualizations
matplotlib>=3.5.0
seaborn>=0.11.0
plotly>=5.0.0

# Web framework
streamlit>=1.28.0

# PDF generation
fpdf2>=2.7.0

# Progress bars
tqdm>=4.64.0

# Optional dependencies
pikepdf>=8.0.0  # For PDF/A compliance
"""
    
    nom_fichier = 'requirements.txt'
    try:
        with open(nom_fichier, 'w', encoding='utf-8') as f:
            f.write(requirements.strip())
        
        print(f"✅ Fichier requirements.txt créé")
        return nom_fichier
        
    except Exception as e:
        print(f"❌ Erreur création requirements.txt : {e}")
        return None

def main():
    """
    Fonction principale qui orchestre l'analyse complète avec génération PDF.
    """
    print("🚀 LANCEMENT ANALYSE ML CLUSTERING MUSICAL + PDF")
    print(f"⏰ Début: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # Installation des dépendances
        installer_dependances()
        
        # Chargement des données
        df_spotify = charger_donnees_spotify()
        
        # Analyse complète du clustering
        resultats = analyser_clustering_complet(df_spotify)
        
        # Analyse des résultats
        analyses = analyser_resultats(resultats)
        
        if analyses:
            # Sauvegarde du meilleur modèle pour le déploiement
            chemins_modeles = sauvegarder_meilleur_modele(analyses['meilleur_modele'])
            
            # Génération du rapport PDF
            if PDF_AVAILABLE:
                rapport_pdf = RapportPDF()
                fichier_pdf = rapport_pdf.generer_rapport(analyses)
                
                if fichier_pdf:
                    print(f"📄 Rapport PDF généré : {fichier_pdf}")
            else:
                print("⚠️ fpdf2 non disponible - Rapport PDF non généré")
            
            # Création du script Streamlit
            script_streamlit = creer_script_streamlit()
            
            # Création du fichier requirements.txt
            fichier_requirements = creer_fichier_requirements()
            
            print(f"\n🎉 ANALYSE TERMINÉE AVEC SUCCÈS!")
            print(f"📊 {len(resultats):,} configurations testées")
            print(f"🏆 Meilleur modèle : {analyses['meilleur_modele']['modele_clustering']}")
            print(f"⏰ Fin: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            
            # Résumé des fichiers générés
            print(f"\n📁 FICHIERS GÉNÉRÉS :")
            print(f"   • resultats_clustering_complets.csv")
            print(f"   • top5_configurations.csv")
            if fichier_pdf:
                print(f"   • {fichier_pdf}")
            if script_streamlit:
                print(f"   • {script_streamlit}")
            if fichier_requirements:
                print(f"   • {fichier_requirements}")
            print(f"   • modeles_deploiement/ (dossier)")
            
            return analyses
            
        else:
            print("❌ Aucun résultat à analyser")
            return None
        
    except Exception as e:
        print(f"❌ ERREUR GÉNÉRALE : {e}")
        import traceback
        traceback.print_exc()
        return None

# Point d'entrée du script
if __name__ == "__main__":
    resultats_finaux = main()

🚀 LANCEMENT ANALYSE ML CLUSTERING MUSICAL + PDF
⏰ Début: 2025-06-24 11:31:24
✓ tqdm disponible
✓ fpdf2 disponible

✓ streamlit disponible
✓ Données chargées: ../Datasets/df_concat_tagged.csv
✓ Shape: (5403, 18)
🎵 DÉBUT ANALYSE CLUSTERING MUSICAL
📊 Données: 5,403 lignes, 18 colonnes

🎯 TRAITEMENT CAS1 - 7 features
   🧹 Nettoyage: 5,403 lignes avant
   ✅ Nettoyage: 5,403 lignes après
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🎯 TRAITEMENT CAS2 - 6 features
   🧹 Nettoyage: 5,403 lignes avant
   ✅ Nettoyage: 5,403 lignes après
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🎯 TRAITEMENT CAS3 - 5 features
   🧹 Nettoyage: 5,403 lignes avant
   ✅ Nettoyage: 5,403 lignes après
   🔧 Preprocessing avec StandardScaler
   🔧 Preprocessing avec MinMaxScaler
   🔧 Preprocessing avec RobustScaler

🏁 TESTS TERMINÉS:
   • Configurations testées: 166
   • Durée totale: 264.7s

📊 ANALYSE RÉSULTATS - 166 configurations

🏆 TOP 5 MEILLEURES CONFIGURATIONS:
================================================================================

🥇 RANG #1
   Modèle: DBSCAN
   Paramètres: eps=1.5, min_samples=3.0
   Cas: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.9014
   Silhouette: 0.8005
   Davies-Bouldin: 0.4314
   Calinski-Harabasz: 3472722.33

🥇 RANG #2
   Modèle: KMeans
   Paramètres: k_clusters=2.0
   Cas: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.7051
   Silhouette: 0.9616
   Davies-Bouldin: 0.1673
   Calinski-Harabasz: 59105.10

🥇 RANG #3
   Modèle: KMeans
   Paramètres: k_clusters=3.0
   Cas: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6733
   Silhouette: 0.9523
   Davies-Bouldin: 0.3279
   Calinski-Harabasz: 90981.01

🥇 RANG #4
   Modèle: KMeans
   Paramètres: k_clusters=25.0
   Cas: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6701
   Silhouette: 0.8683
   Davies-Bouldin: 0.4674
   Calinski-Harabasz: 654560.92

🥇 RANG #5
   Modèle: KMeans
   Paramètres: k_clusters=20.0
   Cas: cas1 (7 features)
   Scaler: RobustScaler
   Score composite: 0.6641
   Silhouette: 0.9012
   Davies-Bouldin: 0.4812
   Calinski-Harabasz: 507085.60

💾 Fichiers CSV sauvegardés
✅ Modèle sauvegardé dans modeles_deploiement/
📄 Génération du rapport PDF...
❌ Erreur génération PDF : Character "•" at index 300 in text is outside the range of characters supported by the font used: "helvetica". Please consider using a Unicode font.
✅ Script Streamlit créé : app_streamlit.py

📋 INSTRUCTIONS DE DÉPLOIEMENT :
1. Installez les dépendances : pip install streamlit plotly
2. Lancez l'application : streamlit run app_streamlit.py
3. L'application sera accessible sur http://localhost:8501
✅ Fichier requirements.txt créé

🎉 ANALYSE TERMINÉE AVEC SUCCÈS!
📊 166 configurations testées
🏆 Meilleur modèle : DBSCAN
⏰ Fin: 2025-06-24 11:35:54

📁 FICHIERS GÉNÉRÉS :
   • resultats_clustering_complets.csv
   • top5_configurations.csv
   • app_streamlit.py
   • requirements.txt
   • modeles_deploiement/ (dossier)

#### Résultats

In [ ]:
# ANALYSE DES RÉSULTATS DE CLUSTERING - TOP 5 CONFIGURATIONS
# =========================================================

"""
ANALYSE DÉTAILLÉE DES PERFORMANCES DE CLUSTERING

Ce top 5 représente les meilleures configurations trouvées lors de l'optimisation
des hyperparamètres pour différents algorithmes de clustering sur le dataset musical.
"""

# RANG #1 - DBSCAN (MEILLEURE CONFIGURATION GLOBALE)
# Configuration: eps=1.5, min_samples=3, cas1 (7 features), RobustScaler
# Score composite: 0.9014 (excellent)
# - DBSCAN excelle car il détecte automatiquement le nombre de clusters
# - eps=1.5 : distance maximale entre points pour être dans le même cluster
# - min_samples=3 : nombre minimum de points pour former un cluster dense
# - Silhouette=0.8005 : très bonne séparation des clusters (proche de 1)
# - Davies-Bouldin=0.4314 : faible valeur = clusters bien séparés et compacts
# - Calinski-Harabasz=3472722.33 : très élevé = excellente définition des clusters

# RANG #2 - KMeans avec 2 clusters
# Configuration: k=2, cas1 (7 features), RobustScaler
# Score composite: 0.7051 (bon)
# - KMeans avec seulement 2 clusters = segmentation très simple
# - Silhouette=0.9616 : excellente (la plus haute du top 5)
# - Davies-Bouldin=0.1673 : très faible = séparation parfaite entre les 2 groupes
# - Peut-être trop simpliste pour la complexité musicale réelle

# RANG #3 - KMeans avec 3 clusters  
# Configuration: k=3, cas1 (7 features), RobustScaler
# Score composite: 0.6733 (correct)
# - Équilibre entre simplicité (3 clusters) et granularité
# - Silhouette=0.9523 : excellente cohésion interne
# - Potentiellement plus réaliste que 2 clusters pour la musique

# RANG #4 - KMeans avec 25 clusters
# Configuration: k=25, cas1 (7 features), RobustScaler  
# Score composite: 0.6701 (correct)
# - Segmentation très granulaire (25 groupes musicaux)
# - Silhouette=0.8683 : encore très bonne malgré la complexité
# - Davies-Bouldin=0.4674 : légère dégradation due au nombre élevé de clusters

# RANG #5 - KMeans avec 20 clusters
# Configuration: k=20, cas1 (7 features), RobustScaler
# Score composite: 0.6641 (correct)
# - Compromis entre granularité et performance
# - Silhouette=0.9012 : excellente cohésion
# - Calinski-Harabasz=507085.60 : bonne définition malgré la complexité

# OBSERVATIONS TRANSVERSALES
# =========================
# 1. RobustScaler optimal pour toutes les configurations
#    - Résistant aux outliers fréquents dans les données audio
#    - Normalisation basée sur la médiane et les quartiles
#
# 2. cas1 (7 features) systématiquement le meilleur
#    - Sélection optimale des caractéristiques musicales
#    - Évite la malédiction de la dimensionnalité
#
# 3. Dominance de KMeans dans le top 5
#    - Algorithme stable et déterministe
#    - Performance constante sur différents nombres de clusters


# JUSTIFICATION DU CHOIX DES MÉTRIQUES DE CLUSTERING
# =================================================

def explication_metriques_clustering():
    """
    Explique pourquoi utiliser ces métriques spécifiques pour évaluer
    la qualité du clustering dans le contexte musical.
    """
    
    # SCORE COMPOSITE - Métrique principale de classement
    # - Combine plusieurs métriques en un seul indicateur
    # - Permet une comparaison objective entre configurations différentes
    # - Formule généralement: moyenne pondérée des métriques normalisées
    # - AVANTAGE: vision globale de la performance
    # - INCONVÉNIENT: peut masquer des faiblesses spécifiques
    
    # SILHOUETTE SCORE - Mesure la cohésion et séparation
    # - Plage: [-1, 1], plus proche de 1 = meilleur
    # - Pour chaque point: (distance inter-cluster - distance intra-cluster) / max(les deux)
    # - AVANTAGE: intuitive, mesure la "qualité naturelle" du clustering
    # - INCONVÉNIENT: sensible à la forme des clusters (favorise les formes sphériques)
    # - MUSICAL: évalue si les chansons similaires sont bien groupées ensemble
    
    # DAVIES-BOULDIN INDEX - Évalue la compacité vs séparation
    # - Plage: [0, +∞], plus proche de 0 = meilleur
    # - Moyenne des ratios: (dispersion cluster i + dispersion cluster j) / distance entre centres
    # - AVANTAGE: ne dépend pas du nombre de points, rapide à calculer
    # - INCONVÉNIENT: assume des clusters convexes et de densité similaire
    # - MUSICAL: vérifie que les genres musicaux sont bien distincts et homogènes
    
    # CALINSKI-HARABASZ INDEX - Mesure la variance entre/intra clusters
    # - Plage: [0, +∞], plus élevé = meilleur
    # - Ratio: variance inter-clusters / variance intra-clusters
    # - AVANTAGE: favorise les clusters denses et bien séparés
    # - INCONVÉNIENT: sensible au nombre de clusters et à la dimensionnalité
    # - MUSICAL: assure que les styles musicaux sont clairement définis
    
    # POURQUOI CES 3 MÉTRIQUES ENSEMBLE ?
    # - Silhouette: perspective "utilisateur" (cohérence perçue)
    # - Davies-Bouldin: perspective "géométrique" (optimisation spatiale)  
    # - Calinski-Harabasz: perspective "statistique" (variance expliquée)
    # - COMPLÉMENTARITÉ: couvrent différents aspects de la qualité
    # - ROBUSTESSE: évitent les biais d'une métrique unique


# RECOMMANDATIONS POUR LA SUITE DU PROJET
# =======================================

def recommandations_implementation():
    """
    Conseils pour exploiter ces résultats dans le système de recommandation musical.
    """
    
    # CHOIX DE LA CONFIGURATION FINALE
    # - RANG #1 (DBSCAN) pour l'exploration exploratoire
    #   * Découvre automatiquement les micro-genres
    #   * Gère bien les outliers (chansons atypiques)
    #   * Idéal pour l'analyse de nouveaux datasets
    
    # - RANG #2-3 (KMeans 2-3 clusters) pour l'interface utilisateur
    #   * Simplicité d'interprétation pour l'utilisateur final
    #   * Catégorisation intuitive (ex: Calme/Énergique/Intermédiaire)
    #   * Performance en temps réel excellente
    
    # - RANG #4-5 (KMeans 20-25 clusters) pour les recommandations fines
    #   * Granularité adaptée aux nuances musicales
    #   * Permet des suggestions très précises
    #   * Équilibre complexité/interprétabilité
    
    # VALIDATION SUPPLÉMENTAIRE RECOMMANDÉE
    # 1. Test sur données de validation temporelle (chansons récentes)
    # 2. Évaluation qualitative par des experts musicaux  
    # 3. A/B testing avec utilisateurs réels
    # 4. Analyse de la stabilité des clusters dans le temps

# MÉTHODE D'OPTIMISATION UTILISÉE (HYPOTHÈSE)
# ===========================================
# Probablement GridSearchCV ou RandomizedSearchCV avec:
# - Cross-validation temporelle pour éviter le data leakage
# - Stratification par genre musical si labels disponibles
# - Optimisation multi-objectifs (score composite)
# - Validation des hyperparamètres sur ensemble de test séparé

##### Résultats globaux

In [14]:
df_resultats_globaux = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/resultats_clustering_complets.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_resultats_globaux

,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,duree_calcul_sec,timestamp,modele_objet,cas,features_count,features_list,...,k_clusters,eps,min_samples,X_clean,n_clusters_detectes,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,0.342094,1.347416,2118.826048,5403,0.959460,2025-06-24 11:31:29,"KMeans(n_clusters=2, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,2.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.556528,0.217596,6.086347e-04,0.288073
1,0.276683,1.230408,1986.473428,5403,0.982092,2025-06-24 11:31:30,"KMeans(n_clusters=3, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,3.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.509703,0.295173,5.705225e-04,0.292604
2,0.198888,1.501536,1787.099613,5403,1.252303,2025-06-24 11:31:31,"KMeans(n_clusters=4, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,4.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.454013,0.115415,5.131111e-04,0.216384
3,0.193390,1.404206,1655.312477,5403,0.993619,2025-06-24 11:31:32,"KMeans(n_clusters=5, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,5.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.450078,0.179945,4.751618e-04,0.234157
4,0.190992,1.326393,1450.366250,5403,1.346908,2025-06-24 11:31:34,"KMeans(n_clusters=7, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,7.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.448361,0.231535,4.161457e-04,0.248930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,-0.133542,1.193926,78.603442,1054,0.082370,2025-06-24 11:35:46,"DBSCAN(eps=0.3, min_samples=10)",cas3,5,"valence, energy, danceability, acousticness, t...",...,NaN,0.3,10.0,valence energy danceability acousticn...,25.0,0.0,0.216041,0.319361,2.113429e-05,0.182231
162,-0.230535,0.846615,8.058357,5232,0.766463,2025-06-24 11:35:47,DBSCAN(min_samples=3),cas3,5,"valence, energy, danceability, acousticness, t...",...,NaN,0.5,3.0,valence energy danceability acousticn...,14.0,0.0,0.146608,0.549629,8.202005e-07,0.223532
163,0.185849,0.612405,16.484363,5136,0.584173,2025-06-24 11:35:48,DBSCAN(),cas3,5,"valence, energy, danceability, acousticness, t...",...,NaN,0.5,5.0,valence energy danceability acousticn...,4.0,0.0,0.444679,0.704910,3.246544e-06,0.389346
164,-0.071282,0.917260,23.791211,5049,0.591160,2025-06-24 11:35:48,DBSCAN(min_samples=7),cas3,5,"valence, energy, danceability, acousticness, t...",...,NaN,0.5,7.0,valence energy danceability acousticn...,5.0,0.0,0.260610,0.502791,5.350617e-06,0.255083
165,0.400192,0.530824,48.623634,4912,0.640721,2025-06-24 11:35:49,DBSCAN(min_samples=10),cas3,5,"valence, energy, danceability, acousticness, t...",...,NaN,0.5,10.0,valence energy danceability acousticn...,2.0,0.0,0.598117,0.758999,1.250134e-05,0.466950

##### Top 5 configurations

In [15]:
df_Top_5_configurations = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/top5_configurations.csv")

# chemin sur windows : df = pd.read_csv("C:/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/top5_meilleurs_modeles.csv")

df_Top_5_configurations

,silhouette_score,davies_bouldin_score,calinski_harabasz_score,n_samples,duree_calcul_sec,timestamp,modele_objet,cas,features_count,features_list,...,k_clusters,eps,min_samples,X_clean,n_clusters_detectes,noise_points,sil_norm,db_norm,ch_norm,score_composite
0,0.800550,0.431446,3.472722e+06,4623,1.015400,2025-06-24 11:32:39,"DBSCAN(eps=1.5, min_samples=3)",cas1,7,"valence, energy, danceability, acousticness, t...",...,NaN,1.5,3.0,valence energy danceability acousticn...,24.0,0.0,0.884716,0.824887,1.000000,0.901352
1,0.961593,0.167324,5.910510e+04,5403,0.788571,2025-06-24 11:32:24,"KMeans(n_clusters=2, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,2.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,1.000000,1.000000,0.017018,0.705106
2,0.952270,0.327891,9.098101e+04,5403,0.795887,2025-06-24 11:32:25,"KMeans(n_clusters=3, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,3.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.993326,0.893544,0.026197,0.673253
3,0.868258,0.467364,6.545609e+05,5403,1.508641,2025-06-24 11:32:32,"KMeans(n_clusters=25, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,25.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.933185,0.801073,0.188485,0.670141
4,0.901174,0.481162,5.070856e+05,5403,1.259870,2025-06-24 11:32:31,"KMeans(n_clusters=20, n_init=10, random_state=42)",cas1,7,"valence, energy, danceability, acousticness, t...",...,20.0,NaN,NaN,valence energy danceability acousticn...,NaN,NaN,0.956749,0.791925,0.146018,0.664082

# Déploiment ML

In [ ]:
# INTÉGRATION DE VOTRE MODÈLE ML DANS VOTRE APPLICATION STREAMLIT EXISTANTE
import pandas as pd
import numpy as np
import pickle
import streamlit as st
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# CLASSE POUR LA RECOMMANDATION SONG-TO-SONG
class MoodifyRecommender:
    """
    Système de recommandation basé sur votre modèle de clustering ML entraîné
    """
    
    def __init__(self, model_path, data_path):
        """
        Initialise le système de recommandation
        
        Arguments:
        model_path : Chemin vers votre fichier .pkl du modèle entraîné
        data_path : Chemin vers vos données Spotify complètes
        """
        self.model_info = self.charger_modele(model_path)
        self.df_songs = pd.read_csv(data_path)
        self.features = self.model_info['features'] if self.model_info else []
        self.songs_processed = None
        self.clusters_assigned = None
        
        if self.model_info:
            self.preparer_donnees()
    
    def charger_modele(self, model_path):
        """
        Charge votre modèle ML entraîné
        
        Arguments:
        model_path : Chemin vers le fichier .pkl
        
        Retourne:
        dict : Informations du modèle ou None si erreur
        """
        try:
            with open(model_path, 'rb') as f:
                model_info = pickle.load(f)
            return model_info
        except Exception as e:
            st.error(f"Erreur lors du chargement du modèle: {e}")
            return None
    
    def preparer_donnees(self):
        """
        Prépare les données avec le même preprocessing que l'entraînement
        """
        try:
            # Sélection des features utilisées par le modèle
            self.songs_processed = self.df_songs[self.features].copy()
            
            # Nettoyage des données
            self.songs_processed = self.songs_processed.dropna()
            
            # Application du preprocessing avec le pipeline du modèle
            self.clusters_assigned = self.model_info['pipeline'].predict(self.songs_processed)
            
            # Ajout des clusters au DataFrame
            self.df_songs_with_clusters = self.df_songs.iloc[self.songs_processed.index].copy()
            self.df_songs_with_clusters['cluster'] = self.clusters_assigned
            
            # Préparation des données scalées pour le calcul de similarité
            self.songs_scaled = self.model_info['pipeline'].named_steps['scaler'].transform(self.songs_processed)
            
        except Exception as e:
            st.error(f"Erreur lors de la préparation des données: {e}")
    
    def rechercher_chanson(self, query, search_by='track_name'):
        """
        Recherche une chanson dans le dataset
        
        Arguments:
        query : Terme de recherche
        search_by : Colonne pour la recherche ('track_name', 'artist_name', etc.)
        
        Retourne:
        DataFrame : Chansons correspondantes
        """
        if search_by not in self.df_songs_with_clusters.columns:
            return pd.DataFrame()
        
        # Recherche insensible à la casse
        mask = self.df_songs_with_clusters[search_by].str.contains(query, case=False, na=False)
        results = self.df_songs_with_clusters[mask]
        
        return results.head(10)  # Limiter à 10 résultats
    
    def recommander_songs_similaires(self, song_index, n_recommendations=5, method='cluster_cosine'):
        """
        Recommande des chansons similaires basées sur votre modèle ML
        
        Arguments:
        song_index : Index de la chanson de référence
        n_recommendations : Nombre de recommandations
        method : Méthode de recommandation ('cluster_cosine', 'cluster_euclidean', 'global_cosine')
        
        Retourne:
        DataFrame : Chansons recommandées
        """
        if song_index not in self.df_songs_with_clusters.index:
            return pd.DataFrame()
        
        song_cluster = self.df_songs_with_clusters.loc[song_index, 'cluster']
        song_features = self.songs_scaled[self.songs_processed.index.get_loc(song_index)].reshape(1, -1)
        
        if method == 'cluster_cosine':
            # Recommandations basées sur le cluster + similarité cosine
            cluster_songs = self.df_songs_with_clusters[
                (self.df_songs_with_clusters['cluster'] == song_cluster) & 
                (self.df_songs_with_clusters.index != song_index)
            ]
            
            if len(cluster_songs) == 0:
                return pd.DataFrame()
            
            # Calcul de similarité cosine dans le cluster
            cluster_indices = [self.songs_processed.index.get_loc(idx) for idx in cluster_songs.index]
            cluster_features = self.songs_scaled[cluster_indices]
            
            similarities = cosine_similarity(song_features, cluster_features)[0]
            
        elif method == 'cluster_euclidean':
            # Recommandations basées sur le cluster + distance euclidienne
            cluster_songs = self.df_songs_with_clusters[
                (self.df_songs_with_clusters['cluster'] == song_cluster) & 
                (self.df_songs_with_clusters.index != song_index)
            ]
            
            if len(cluster_songs) == 0:
                return pd.DataFrame()
            
            cluster_indices = [self.songs_processed.index.get_loc(idx) for idx in cluster_songs.index]
            cluster_features = self.songs_scaled[cluster_indices]
            
            distances = euclidean_distances(song_features, cluster_features)[0]
            similarities = 1 / (1 + distances)  # Conversion en similarité
            
        else:  # global_cosine
            # Recommandations sur tout le dataset
            cluster_songs = self.df_songs_with_clusters[self.df_songs_with_clusters.index != song_index]
            
            all_indices = [self.songs_processed.index.get_loc(idx) for idx in cluster_songs.index]
            all_features = self.songs_scaled[all_indices]
            
            similarities = cosine_similarity(song_features, all_features)[0]
        
        # Tri par similarité décroissante
        similar_indices = np.argsort(similarities)[::-1][:n_recommendations]
        recommended_songs = cluster_songs.iloc[similar_indices].copy()
        recommended_songs['similarity_score'] = similarities[similar_indices]
        
        return recommended_songs
    
    def get_song_profile(self, song_index):
        """
        Obtient le profil détaillé d'une chanson
        
        Arguments:
        song_index : Index de la chanson
        
        Retourne:
        dict : Profil de la chanson
        """
        if song_index not in self.df_songs_with_clusters.index:
            return {}
        
        song_data = self.df_songs_with_clusters.loc[song_index]
        song_cluster = song_data['cluster']
        
        # Profil du cluster
        cluster_profile = self.model_info.get('cluster_profiles', {}).get(song_cluster, {})
        
        # Features de la chanson
        song_features = {feature: song_data.get(feature, 0) for feature in self.features}
        
        return {
            'song_info': song_data.to_dict(),
            'cluster': song_cluster,
            'cluster_profile': cluster_profile,
            'features': song_features
        }

# FONCTION D'INTÉGRATION DANS VOTRE APPLICATION STREAMLIT
def ajouter_fonction_recommandation_ml():
    """
    Fonction à intégrer dans votre application Streamlit existante
    pour ajouter la recommandation basée sur votre modèle ML
    """
    
    st.header("🎯 Recommandation Intelligente (ML)")
    st.markdown("*Basée sur votre modèle de clustering entraîné*")
    
    # Initialisation du recommandeur (à adapter selon vos chemins)
    if 'recommender' not in st.session_state:
        try:
            # MODIFIEZ CES CHEMINS SELON VOS FICHIERS
            model_path = '/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Datasets/modeles_deploiement/best_model.pkl'  # Votre modèle entraîné
            data_path = '/Users/beber/Documents/Cours/Wild_Code_School/Semaine_8_Visualisation_interactive_&_Pandas_approfondi/Projet_2/Projet_2_local/Notebooks/df_concat_tagged.csv'  # Vos données complètes
            
            st.session_state.recommender = MoodifyRecommender(model_path, data_path)
            
            if st.session_state.recommender.model_info is None:
                st.error("❌ Impossible de charger le modèle ML")
                return
                
        except Exception as e:
            st.error(f"❌ Erreur d'initialisation: {e}")
            return
    
    recommender = st.session_state.recommender
    
    # Interface de recherche
    col1, col2 = st.columns([2, 1])
    
    with col1:
        search_query = st.text_input(
            "🔍 Rechercher une chanson:",
            placeholder="Nom de la chanson ou de l'artiste...",
            help="Tapez le nom d'une chanson ou d'un artiste pour commencer"
        )
    
    with col2:
        search_type = st.selectbox(
            "Rechercher par:",
            options=['track_name', 'artist_name'],
            format_func=lambda x: 'Titre' if x == 'track_name' else 'Artiste'
        )
    
    # Recherche et affichage des résultats
    if search_query:
        search_results = recommender.rechercher_chanson(search_query, search_type)
        
        if not search_results.empty:
            st.subheader("📋 Résultats de recherche")
            
            # Affichage des résultats sous forme de sélection
            selected_songs = []
            for idx, song in search_results.iterrows():
                col_select, col_info = st.columns([1, 4])
                
                with col_select:
                    if st.button(f"▶️", key=f"select_{idx}"):
                        st.session_state.selected_song_idx = idx
                
                with col_info:
                    # Informations de base disponibles dans la plupart des datasets
                    song_info = f"**{song.get('track_name', 'Titre inconnu')}**"
                    if 'artist_name' in song:
                        song_info += f" - {song['artist_name']}"
                    if 'album_name' in song:
                        song_info += f" ({song['album_name']})"
                    if 'year' in song or 'release_date' in song:
                        year = song.get('year', song.get('release_date', ''))
                        song_info += f" [{year}]"
                    
                    st.markdown(song_info)
        else:
            st.warning("🔍 Aucune chanson trouvée. Essayez un autre terme de recherche.")
    
    # Affichage des recommandations si une chanson est sélectionnée
    if 'selected_song_idx' in st.session_state:
        selected_idx = st.session_state.selected_song_idx
        
        # Profil de la chanson sélectionnée
        song_profile = recommender.get_song_profile(selected_idx)
        
        if song_profile:
            st.markdown("---")
            st.subheader("🎵 Chanson Sélectionnée")
            
            col_song, col_cluster = st.columns([2, 1])
            
            with col_song:
                song_info = song_profile['song_info']
                st.markdown(f"**🎼 {song_info.get('track_name', 'Titre inconnu')}**")
                if 'artist_name' in song_info:
                    st.markdown(f"👤 **Artiste:** {song_info['artist_name']}")
                if 'album_name' in song_info:
                    st.markdown(f"💿 **Album:** {song_info['album_name']}")
            
            with col_cluster:
                st.metric("🎯 Cluster ML", f"#{song_profile['cluster']}")
            
            # Options de recommandation
            st.subheader("⚙️ Options de Recommandation")
            
            col_method, col_num = st.columns([2, 1])
            
            with col_method:
                rec_method = st.selectbox(
                    "Méthode:",
                    options=['cluster_cosine', 'cluster_euclidean', 'global_cosine'],
                    format_func=lambda x: {
                        'cluster_cosine': '🎯 Même cluster + Similarité Cosine',
                        'cluster_euclidean': '🎯 Même cluster + Distance Euclidienne', 
                        'global_cosine': '🌐 Recherche globale + Similarité Cosine'
                    }[x]
                )
            
            with col_num:
                n_recs = st.slider("Nombre:", 3, 10, 5)
            
            # Génération des recommandations
            if st.button("🚀 Générer des Recommandations", type="primary"):
                with st.spinner("🎵 Analyse en cours..."):
                    recommendations = recommender.recommander_songs_similaires(
                        selected_idx, n_recs, rec_method
                    )
                
                if not recommendations.empty:
                    st.subheader("🎁 Recommandations")
                    
                    for i, (idx, rec) in enumerate(recommendations.iterrows(), 1):
                        with st.expander(f"#{i} - {rec.get('track_name', 'Titre inconnu')} (Score: {rec.get('similarity_score', 0):.3f})"):
                            col_rec_info, col_rec_score = st.columns([3, 1])
                            
                            with col_rec_info:
                                if 'artist_name' in rec:
                                    st.write(f"👤 **Artiste:** {rec['artist_name']}")
                                if 'album_name' in rec:
                                    st.write(f"💿 **Album:** {rec['album_name']}")
                                if 'year' in rec or 'release_date' in rec:
                                    year = rec.get('year', rec.get('release_date', ''))
                                    st.write(f"📅 **Année:** {year}")
                                
                                # Affichage des features si disponibles
                                if recommender.features:
                                    st.write("🎵 **Caractéristiques:**")
                                    feature_cols = st.columns(len(recommender.features[:4]))  # Limiter à 4 colonnes
                                    for j, feature in enumerate(recommender.features[:4]):
                                        if feature in rec:
                                            with feature_cols[j]:
                                                st.metric(feature.title(), f"{rec[feature]:.2f}")
                            
                            with col_rec_score:
                                st.metric("🎯 Similarité", f"{rec.get('similarity_score', 0):.3f}")
                                st.metric("🏷️ Cluster", f"#{rec.get('cluster', 'N/A')}")
                else:
                    st.warning("❌ Aucune recommandation trouvée avec ces paramètres.")

# CODE D'INTÉGRATION DANS VOTRE APPLICATION EXISTANTE
def integrer_dans_app_existante():
    """
    Code à ajouter dans votre application Streamlit existante
    """
    
    # AJOUTEZ CETTE SECTION DANS VOTRE FICHIER APP.PY EXISTANT
    
    # Dans votre sidebar ou menu principal, ajoutez:
    page = st.sidebar.selectbox(
        "Navigation",
        ["Accueil", "Recommandation ML", "Autres fonctions..."]  # Ajoutez vos pages existantes
    )
    
    if page == "Recommandation ML":
        ajouter_fonction_recommandation_ml()
    
    # OU directement dans une section de votre page:
    # st.markdown("---")
    # ajouter_fonction_recommandation_ml()

# EXEMPLE D'UTILISATION COMPLÈTE
def exemple_integration_complete():
    """
    Exemple complet d'intégration dans une application Streamlit
    """
    
    st.set_page_config(
        page_title="Votre App Musicale",
        page_icon="🎵",
        layout="wide"
    )
    
    # Votre header existant
    st.title("🎵 Votre Application Musicale")
    
    # Navigation par onglets
    tab1, tab2, tab3 = st.tabs(["🏠 Accueil", "🎯 Recommandation ML", "📊 Statistiques"])
    
    with tab1:
        st.write("Contenu de votre page d'accueil existante...")
    
    with tab2:
        # VOTRE NOUVELLE FONCTION DE RECOMMANDATION ML
        ajouter_fonction_recommandation_ml()
    
    with tab3:
        st.write("Vos autres fonctionnalités existantes...")

# INSTRUCTIONS D'INTÉGRATION
"""
INSTRUCTIONS POUR INTÉGRER VOTRE MODÈLE ML:

1. PRÉREQUIS:
   - Votre modèle entraîné sauvegardé en .pkl (avec pipeline complet)
   - Votre dataset complet des chansons en CSV
   - Les colonnes 'track_name', 'artist_name' dans votre dataset

2. ÉTAPES D'INTÉGRATION:
   
   a) Copiez la classe MoodifyRecommender dans votre fichier app.py
   
   b) Modifiez les chemins dans ajouter_fonction_recommandation_ml():
      model_path = 'VOTRE_CHEMIN/best_model.pkl'
      data_path = 'VOTRE_CHEMIN/df_concat_tagged.csv'
   
   c) Ajoutez l'appel à ajouter_fonction_recommandation_ml() dans votre app:
      - Soit dans un nouvel onglet
      - Soit dans une nouvelle section
      - Soit dans une nouvelle page

3. TEST:
   streamlit run votre_app.py

4. FONCTIONNALITÉS AJOUTÉES:
   ✅ Recherche de chansons par titre/artiste
   ✅ Recommandations basées sur votre modèle ML
   ✅ 3 méthodes de recommandation différentes
   ✅ Scores de similarité
   ✅ Profils des chansons et clusters
   ✅ Interface intuitive intégrée

Cette approche vous permet d'ajouter facilement la recommandation ML
à votre application existante sans tout reconstruire !
"""

if __name__ == "__main__":
    # Pour tester indépendamment
    exemple_integration_complete()

2025-06-24 11:35:56.249
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\beber\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-06-24 11:35:56.249 Session state does not function when running a script without `streamlit run`